### ISSUE TITLE
Pass both frontmatter and body field for md and mdx content

### ISSUE THREAD

**Issue by timlrx** [contentlayerdev/contentlayer#106]
It seems that contentlayer [parses out the fields](https://github.com/contentlayerdev/contentlayer/blob/main/packages/@contentlayer/source-files/src/fetchData/mapping.ts#L46) from md and mdx content and only the body of the content is subsequently passed to `markdownToHtml` or `bundleMDX`.

This causes an issue with downstream plugins that rely on the frontmatter properties of the document. Could we pass the entire md/mdx file as the body? Thanks.

For example the following mdx document:

```
---
title: Sample .md file
date: '2016-03-08'
---

A sample post with markdown.
```

produces the following mdast from contentlayer (logged at the first task of `remarkPlugins`):

```
{
  type: 'root',
  children: [
    { type: 'paragraph', children: [Array], position: [Object] }
  ],
  position: {
    start: { line: 1, column: 1, offset: 0 },
    end: { line: 3, column: 1, offset: 30 }
  }
}
```

Using `mdx-bundler` directly gives the following output:

```
{
  type: 'root',
  children: [
    { type: 'mdxjsEsm', value: '', data: [Object] },
    {
      type: 'yaml',
      value: "title: Sample .md file\ndate: '2016-03-08'",
      position: [Object]
    },
    { type: 'paragraph', children: [Array], position: [Object] }
  ],
  position: {
    start: { line: 1, column: 1, offset: 0 },
    end: { line: 7, column: 1, offset: 89 }
  }
}
```

**Comment by schickling** [comment]
This problem should now be addressed with [version `0.1.0`](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.1.0). Contentlayer now passes the full raw document string (incl. the frontmatter) to the MD or MDX pipeline.

 If you're running into problems, please let me know. :)
