### ISSUE TITLE
[ASK] How to re-generate .contentlayer folder after deleted

### ISSUE THREAD

**Issue by hafidzamr** [contentlayerdev/contentlayer#113]
when I have accidentally deleted the folder `.contentlayer` how to re-generate it again? 

because if I want to re-generate I must be removed the `node-modules` folder first.

Reproduction:  

The video maybe will long, so you can skip it until finish installing the module package

https://user-images.githubusercontent.com/49369600/152722545-5c09ea5a-97e4-4e01-83e8-73762cf82fb5.mp4

btw why I'm not using like this
```
import { allBlogs } from '.contentlayer/data';
import { Blog as BlogTypes } from '.contentlayer/types';
```

because this 😢 

![image](https://user-images.githubusercontent.com/49369600/152723407-ea270f6a-d0b5-4192-a0e0-7dc37ef07d3f.png)

[import/no-extraneous-dependencies](https://github.com/import-js/eslint-plugin-import/blob/v2.25.4/docs/rules/no-extraneous-dependencies.md)

**Comment by schickling** [comment]
This problem should now be addressed with [version `0.1.0`](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.1.0). If you're running into problems, please let me know. :)
