### ISSUE TITLE
Scroll position is lost when markdown content is updated

### ISSUE THREAD

**Issue by ghoshnirmalya** [contentlayerdev/contentlayer#124]
## Details
The scroll position of the Next.js page is lost when the content is updated in the related markdown file. The issue has been discussed [in a separate issue](https://github.com/contentlayerdev/contentlayer/issues/109#issuecomment-1035884188). I have created this new issue as per @schickling's [request](https://github.com/contentlayerdev/contentlayer/issues/109#issuecomment-1036452135).

## Context
Please see [this issue](https://github.com/contentlayerdev/contentlayer/issues/109#issuecomment-1036452135) for more context.

**Comment by schickling** [comment]
Thanks a lot for opening this issue @ghoshnirmalya. I'll need to investigate this further but I'm pretty sure this is rather a limitation with Next.js itself than a problem in Contentlayer. However, I'll first need to confirm this hypothesis and want to explore ways to avoid this behaviour. (I've also reached out to the Next.js team about this.)

**Comment by schickling** [comment]
I've opened a PR with a fix in Next.js https://github.com/vercel/next.js/pull/35739

**Comment by elitan** [comment]
I also had this issue with Next 12.0.1. I update to the latest version (12.1.7) and that solved my issue.

I can now make changes to my .mdx files and get live-reload and the scroll position is maintained. 🎉
