### ISSUE TITLE
Generate a warning when jsconfig or tsconfig settings are missing

### ISSUE THREAD

**Issue by lucaslago** [contentlayerdev/contentlayer#132]
When `path` and `baseUrl` are not defined in jsconfig or tsconfig we get these errors which can be a bit misleading:

![image](https://user-images.githubusercontent.com/10089668/156772681-7215499d-5247-4520-a39c-d063bb0fcc55.png)

**Comment by schickling** [comment]
This was just released as part of the new [`0.2.1` version](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.2.1). 🚀 

Feel free to comment in case you're running into any problems or open a new issue.
