### ISSUE TITLE
[more-info-needed] Generated documents in .contentlayer

### ISSUE THREAD

**Issue by abrahamcalsin** [contentlayerdev/contentlayer#134]
When I run my project with `npm run dev`, it does not generate the necessary documents in the .contentlayer folder, I have some .md articles already created.

**Why does this happen?**

I have all the necessary configuration as stated in the official contentlayer documentation.
I am using contentlayer version 0.1.2 with nextjs and typescript.

**Comment by schickling** [comment]
Thanks for opening this issue. Please provide a link to a reproduction repo for someone to look into your problem.

**Comment by abrahamcalsin** [comment]
> Thanks for opening this issue. Please provide a link to a reproduction repo for someone to look into your problem.

@schickling, thanks for replying, I managed to fix the problem, it was my mistake, it was the address of the articles provided in the contentlayer configuration, in filePathPattern and contentDirPath, to generate the necessary documents.
