### ISSUE TITLE
doc arg in computedField resolve functions exposing Effect-TS structures for lists

### ISSUE THREAD

**Issue by mshick** [contentlayerdev/contentlayer#150]
I've defined a regular field for tags, like so: `tags: { type: 'list', of: { type: 'string' }, required: false }`. 

I then have a computedField, `tags`, which is intended to resolve the tags to full urls. I noticed that the value at `doc.tags` appears to be a functional structure, probably from Effect-TS, while I would have expected an array of strings.

```
PlainArr {
  _typeId: Symbol(),
  _array: [ 'tag1', 'tag2' ],
  depth: 0,
  left: <ref *1> Empty {
    depth: 0,
    _typeId: Symbol(),
    left: [Circular *1],
    right: [Circular *1],
    binary: true,
    length: 0,
    arrayCache: [],
    [Symbol()]: Symbol()
  },
  right: <ref *1> Empty {
    depth: 0,
    _typeId: Symbol(),
    left: [Circular *1],
    right: [Circular *1],
    binary: true,
    length: 0,
    arrayCache: [],
    [Symbol()]: Symbol()
  },
  length: 2,
  [Symbol()]: Symbol()
}
```

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!
