### ISSUE TITLE
Field named `type` not supported

### ISSUE THREAD

**Issue by browniefed** [contentlayerdev/contentlayer#168]
It appears that if the frontmatter includes a `type` field this will cause an error, and be or be overwritten by the `defineDocumentType`. 

Ideally this would be able to be disabled, or put into a nested object.

**Comment by schickling** [comment]
Have you tried using the `fieldOptions.typeFieldName` option in `makeSource`?

![CleanShot 2022-04-13 at 11 27 12](https://user-images.githubusercontent.com/1567498/163145500-7207ff69-cf4b-494d-b9af-e2e321fe2805.png)
