### ISSUE TITLE
Can't resolve 'contentlayer/client' in generated files

### ISSUE THREAD

**Issue by ph-poppe** [contentlayerdev/contentlayer#177]
I have this issue with the generated file in next.js stack. 

```
.contentlayer/generated/index.mjs:3:0
Module not found: Can't resolve 'contentlayer/client'
  1 | // NOTE This file is auto-generated by Contentlayer
  2 | 
> 3 | export { isType } from 'contentlayer/client'
  4 | 
  5 | // NOTE During development Contentlayer imports from `.mjs` files to improve HMR speeds.
  6 | // During (production) builds Contentlayer it imports from `.json` files to improve build performance.

Import trace for requested module:
./src/pages/blog/[[...slug]].tsx

https://nextjs.org/docs/messages/module-not-found
```

packages installed
- "next": "11.1.3",
- "contentlayer": "^0.2.2",
- "next-contentlayer": "^0.2.2",

tsconfig is implemented as per example:
- paths: {..., "contentlayer/generated": ["./.contentlayer/generated"]},
- include: [...,".contentlayer/generated"]

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

**Comment by ph-poppe** [comment]
hi johannes, 

repo:
https://github.com/ph-poppe/website-dd-marketing

how to reproduce: 

yarn
yarn dev 
http://localhost:8000/blog

page build stops with the above mentioned error

**Comment by schickling** [comment]
Thanks a lot @ph-poppe. This is due to a limitation in Next.js 11 and earlier. Currently `next-contentlayer` only works with Next.js 12 and newer. Is upgrading for Next.js an option for you?

**Comment by ph-poppe** [comment]
it is conflicting with the static "next-optimized-images"optimizer, but it might be best indeed to upgrade next and get this working and find a solution for the static images optimization.
Thanks for the help @schickling! I couldn't find any related issue, so this is a great help.
