### ISSUE TITLE
Error when using different versions of `contentlayer` and `next-contentlayer`: Cannot read property 'cwd' of undefined

### ISSUE THREAD

**Issue by studioprisoner** [contentlayerdev/contentlayer#187]
Build failed on Vercel, with next-contentlayer v0.2.4

Build error log
`TypeError: Cannot read property 'cwd' of undefined`

Full build log https://gist.github.com/studioprisoner/b111b6abc6320539a7208d7ab1ef9057

**Comment by schickling** [comment]
[Context from Discord](https://ptb.discord.com/channels/872106850928164874/872106850928164878/965973679328604270):

<img width="783" alt="image" src="https://user-images.githubusercontent.com/1567498/164021644-985fdd29-5f37-48bf-a46f-0bdf685b7737.png">
