### ISSUE TITLE
Allow custom options to be passed to default Markdown processors

### ISSUE THREAD

**Issue by causztic** [contentlayerdev/contentlayer#202]
From here: https://github.com/contentlayerdev/website/issues/43

# Context

Some platforms like Github allows raw HTML tags to be used in Markdown. This can be useful if creators want to include raw HTML from trusted sources, or want to introduce extra layout and semantic flexibilities that would be hard to implement with only Markdown tags / require extra post-processing. 

# Current Situation

ContentLayer's Markdown processing middleware currently does not provide this possibility.

For this to work in ContentLayer, `remark-rehype` requires an additional option of `{ allowDangerousHtml: true }` , which allows the processor to pass the nodes as-is, so that it can be parsed again either by `rehype-raw` or `rehype-stringify`.

# Proposal

To allow for this to happen, we can allow options specified in `contentlayer.config.js` (maybe something like 
`remarkRehypeOptions` for `remark-rehype`, as an example)  to be passed into the respective default processors. Since this is optional, users will have to be aware of its security implications (if any) and enable them consciously.

**Comment by schickling** [comment]
This should be addressed with the [`0.2.5` release](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.2.5). 🎉
