### ISSUE TITLE
Support content taxonomies

### ISSUE THREAD

**Issue by lucperkins** [contentlayerdev/contentlayer#210]
In line with #209, another Hugo feature I like is its built-in [taxonomies](https://gohugo.io/content-management/taxonomies), which enable you to group your content based on document metadata. When you configure a taxonomy, such as `tags` or `categories`, you can then [template](https://gohugo.io/templates/taxonomy-templates) that taxonomized content in any number of ways. So with a `tags` taxonomy in place, for example, you can pretty easily template out a page at `/blog/tags` and `/blog/tags/fashion` would yield a templated page displaying all the blog posts that have the `fashion` tag. And so on.

Now, I suspect that some of this is already possible with Contentlayer using logic à la `allDocs.filter(...)`. But I do think it may be worth considering adding a specific feature along these lines. Maybe something like this:

```js
export const Post = defineDocumentType(() => ({
  name: 'Post',
  filePathPattern: `**/*.md`,
  fields: {
    title: {
      type: 'string',
      description: 'The title of the post',
      required: true,
    },
  },
  taxonomies: {
    tags: {
      name: 'tag'
    }
  }
}));
```

With this config, Contentlayer would look for documents with a `tags` field in the metadata and create a new sub-object for each value under `tags` that it encounters. Then you could do things like:

```js
// "Query" documents
import { allPosts, Post} from "contentlayer/generated";

const gettingStartedPosts: Post[] = allPosts.taxonomies.tags.find(["getting-started"]);

// Iterate through tags
const allTags: string[] = allPosts.taxonomies.tags.all();
allTags.forEach(tag => ...);

// Iterate through all available taxonomies
allPosts.taxonomies.forEach(taxonomy => {
  console.log(taxonomy.name);
  taxonomy.groups.forEach(group => {
    console.log(group.name);
    console.log(group.items.length);
  });
});
```

This example is off the cuff but hopefully illustrates the kind of thing that I think would be nice to provide. Happy to help out with this if project leads think it's a good idea!

**Comment by schickling** [comment]
Thanks for this feature suggestion. Looking forward to hearing more about this use case from other users!

Possibly also related to #71

**Comment by lucperkins** [comment]
@seancdavis I do think that `filter` would be a reasonable way to accomplish this, and in fact I'm already doing this in a pet project I'm using to learn CL :smile: I think I'm suggesting this as a feature because I'm drawn to a more "compile-time" approach whereby CL provides you the exact stuff you want at build time, but I can also see why extra API surface area is something you want to be vigilant about. One way or another I'll probably end up with my own personal helper library anyway 🤣 I think that your suggested approach of focusing on other work and displaying `filter` logic on configured fields in the docs/examples is probably the right call. Here's what I've essentially done:

```ts
// Config
const Post = defineDocumentType(() => ({
  name: 'Post',
  filePathPattern: '**/*.md',
  fields: {
    title: {
      type: 'string',
      description: 'The title of the post',
      required: true,
    },
    tags: {
      type: 'list',
      of: {
        type: 'string'
      },
      default: [],
      description: 'Blog post tags',
      required: false
    }
  },
}));

export default makeSource({
  contentDirPath: docsPath,
  documentTypes: [Post],
});

// Helper
type Tagged = { tags: string[] };

const hasTag = <T extends Tagged>(items: T[], tag: string): T[] => {
  return items.filter(item => item.tags.includes(tag));
}

// Code
import { allPosts, Post } from 'contentlayer/generated';

const productPosts: Post[] = hasTag(allPosts, 'product');
```

**Comment by lucperkins** [comment]
I've provided a pretty thorough example of using this kind of logic in this PR:

https://github.com/contentlayerdev/next-contentlayer-example/pull/12

I agree with the assessment that this is already possible in CL and will thus close this.
