### ISSUE TITLE
Gitpod Getting Started example not working

### ISSUE THREAD

**Issue by valtism** [contentlayerdev/contentlayer#211]
Tested in MacOS Safari and Chrome. Returns the error `Couldn't parse context 'https:/github.com/contentlayerdev/next-contentlayer-example'.`

**Comment by schickling** [comment]
@valtism thanks for opening this issue. Could you please share where you've seen/found the Gitpod link you've shared above?

It seems to miss a `/` after the `https:/` in the URL you shared. It should be: `http://gitpod.io/#https://github.com/contentlayerdev/next-contentlayer-example`

**Comment by valtism** [comment]
This at the top of the Getting Started page: https://www.contentlayer.dev/docs/getting-started in the "Try It Now" box
