### ISSUE TITLE
Hot reloading not works on windows

### ISSUE THREAD

**Issue by AkashRajpurohit** [contentlayerdev/contentlayer#22]
There is an open issue about contentlayer not working on windows #7 
Based on the [comment here](https://github.com/contentlayerdev/contentlayer/issues/7#issuecomment-961045710), I have installed the 0.0.28-dev.12 version. The package is able to compile in the first run but any modifications in MDX file while in dev mode crashes the script.
This happens for both dev script for Nextjs as well as `yarn contentlayer dev` script.

Attaching a video for demo

https://user-images.githubusercontent.com/30044630/140604382-13bd780a-69be-49fd-9242-8e7386efce14.mp4

**Comment by schickling** [comment]
@AkashRajpurohit I've tried reproducing this (in a Windows VM) but did error didn't occur for me. Could you please provide a minimal repository which I can clone and run to debug this further?

**Comment by AkashRajpurohit** [comment]
Minimal Repro - https://github.com/AkashRajpurohit/contentlayer-minimal-repro
Using the latest version which currently is 0.0.28.

Sharing something which I found while looking at the error message. Looks like when updating mdx file in the watch mode, the dev server is trying to find under different path than what it is present in the `.contenlayer` folder.
Attaching a screenshot for the same
![image](https://user-images.githubusercontent.com/30044630/140757453-1fc03c83-2263-4c65-952d-5b0f1742fd64.png)

**Comment by schickling** [comment]
Thanks a lot for providing all of this information @AkashRajpurohit - this made it a lot easier to reproduce and understand. 🙏 

The latest `dev` version should fix this and will be released soon on `latest`.
