### ISSUE TITLE
Unmet peer dependencies

### ISSUE THREAD

**Issue by shamwela** [contentlayerdev/contentlayer#229]
I love contentlayer but why do I need the `date-fns` package as a peer dependency if I don't use it?
![image](https://user-images.githubusercontent.com/62544170/169457450-8a5cadf8-f56c-436a-83bc-87fe0722c06b.png)

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

**Comment by shamwela** [comment]
Reproduction repository is https://github.com/shamwela/date-fns-reproduction
1. Install pnpm if you haven't. `npm i -g pnpm`
2. Run `pnpm i`

**Comment by shamwela** [comment]
Any update on this?

**Comment by schickling** [comment]
This should be addressed with the [`0.2.6` release](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.2.6). 🎉
