### ISSUE TITLE
Singleton's warn to use Pascal casing for type names, still generate camelCase for imports

### ISSUE THREAD

**Issue by motleydev** [contentlayerdev/contentlayer#231]
I had a `globalMenu` type, that contentlayer warned I should rename to PascalCase. When I did, it still generates camelCase (ie, allDocs, allPages, etc) which I guess is familiar, but for Singletons, I was sort of expecting the the import to be the same name as the type I declared.

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!
