### ISSUE TITLE
Add an option to strip prefix from document paths

### ISSUE THREAD

**Issue by lucperkins** [contentlayerdev/contentlayer#233]
Right now I'm working on an example site for NextJS that has a `content` directory for all content and then individual directories for different content types (`docs`, `blog`, etc.). A pretty common use. One issue I'm running into is that working with path prefixes (`/docs`, `/blog`, etc.) leads to some subtle difficulties. To give an example, I have a `/pages/docs/[slug].tsx` file for fetching specific docs. The slug in that case ends up being `about`, `installation`, etc., but the corresponding paths those slugs should match is `/docs/about`, `/docs/installation`. Here's how I'm currently doing that:

```typescript
const getDoc = (slug: string): Doc | undefined => {
  return allDocs.find(doc => doc._raw.flattenedPath === `docs/`${slug}`);
}
```

Now, this isn't *super* tricky, of course, but personally I would much prefer to be able to strip the prefix so that I could just do this:

```typescript
return allDocs.find(doc => doc._raw.flattenedPath === slug);
```

A config for that could look something like this:

```javascript
export const Doc = defineDocumentType(() => ({
  name: "Doc",
  filePathPattern: "**/*.md",
  prefix: "docs", // New parameter
  fields: {
    title: {
      type: "string",
      description: "The title of the doc",
      required: true,
    }
  },
}));

export default makeSource({
  contentDirPath: "content",
  documentTypes: [Doc],
});
```

With this configuration, CL would know to look for `Doc`s inside of `content/docs` but would produce JSON like this for the `Doc` in `content/docs/about.md`:

```json
{
  "title": "About",
  "body": {
    "raw": "\nHere is some info about  the project.",
    "html": "<p>Here is some info about the project.</p>"
  },
  "_id": "about.md",
  "_raw": {
    "sourceFilePath": "about.md",
    "sourceFileName": "about.md",
    "sourceFileDir": "docs",
    "contentType": "markdown",
    "flattenedPath": "about"
  },
  "type": "Doc",
  "path": "/about"
}
```

One of the benefits would be that it'd be easier to write generic logic for content types. So the `getDoc` function above could become this:

```typescript
const getDocument = <T extends DocumentGen>(items: T[], slug: string): T | undefined => {
  return items.find(doc => doc._raw.flattenedPath === slug);
}

// Use for docs, blog posts, etc.
```

And this could be used in any `pages/{type}/[slug].tsx` without the query logic needing to "know" about the content directory structure. A small quality of life thing, perhaps, but to me this seems more intuitive.

**Comment by schickling** [comment]
Thanks a lot for suggesting this feature. My general preference is to keep the API surface as minimal as possible and be rather conservative in terms of adding more configuration options.

What you're describing should already be possible by using a computed field. Did you consider the following?

```ts
export const Doc = defineDocumentType(() => ({
  name: "Doc",
  filePathPattern: "**/*.md",
  fields: {
    title: {
      type: "string",
      description: "The title of the doc",
      required: true,
    }
  },
  computedFields: {
    slug: {  type: 'string', resolve: (doc) => doc.raw._id.replace(/^docs\//, '') },
  },
}));

export default makeSource({
  contentDirPath: "content",
  documentTypes: [Doc],
});
```

**Comment by lucperkins** [comment]
@schickling 100% agreed that this is unnecessary and already possible under current constraints. I did it a little bit differently for the sake of avoiding the regex:

```ts
path: {
  type: "string",
  resolve: (doc: LocalDocument) => `/${doc._raw.flattenedPath}`,
}
```
