### ISSUE TITLE
Netlify Plugin?

### ISSUE THREAD

**Issue by eligundry** [contentlayerdev/contentlayer#240]
Hey all, I love Contentlayer, y'all are doing great work!

Is there any interest in a Netlify plugin to cache the generated data between builds? I went ahead a coded up a [super ugly version of one as a local plugin](https://github.com/eligundry/eligundry.com/blob/main/next/plugins/netlify-plugin-contentlayer/index.js) that I could clean up and contribute if there is interest? I suspect that this will have marginal impact on file based sources but could yield big speed ups when Contentful/Sanity are ready for primetime.

**Comment by seancdavis** [comment]
Thanks for the thoughts, work, and kind words, @eligundry! 

There is no official plan to build a Netlify plugin as of now. We can use 👍 votes on the issue description to track interest.

That said, if what you're doing is working, I'd suggest [submitting to Netlify](https://docs.netlify.com/integrations/build-plugins/share-plugins/#submit-to-the-plugins-directory) to make it an official plugin. If this request gets enough votes to warrant officially supporting it, we can always ask for a transfer in the future.
