### ISSUE TITLE
Bug: `makeSource` args type not updated with new config options for 0.2.5 release

### ISSUE THREAD

**Issue by Saeris** [contentlayerdev/contentlayer#243]
In the `0.2.5` release notes, for MDX, it's recommended to use a new `mdxOptions` property, but the `PartialArgs` type that `makeSource` expects hasn't been updated for this as far as I can tell. Whereas with the `markdown` field, it was correctly updated to optionally support a builder callback function. Here's a link the relevant code: https://github.com/contentlayerdev/contentlayer/blob/dcc48858f7643f882a72a9cc5941deb36bbb1ecf/packages/%40contentlayer/core/src/plugin.ts#L125-L132

And the release notes where there is a mismatch: https://github.com/contentlayerdev/contentlayer/releases/tag/v0.2.5

Additionally, I'm unsure how this solves the problem I was aiming to resolve with #192

**Comment by seancdavis** [comment]
@Saeris There are two issues on the website repo for better documenting markdown behavior:

- contentlayerdev/website#20
- contentlayerdev/website#43

Do you suspect properly completing those issues would solve this topic here?

**Comment by Saeris** [comment]
This topic is specifically about the types the library is shipping need to be updated. Currently you cannot use `mdxOptions` as documented because it raises a type error. So no, it's not a documentation issue, it's missing code. Either that or the release notes were inaccurate.

**Comment by schickling** [comment]
This should be addressed with the [`0.2.6` release](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.2.6). 🎉
