### ISSUE TITLE
I keep getting "Error module note found" for import { allPosts } from 'contentlayer/generated'

### ISSUE THREAD

**Issue by TreGalloway** [contentlayerdev/contentlayer#245]
<img width="989" alt="CleanShot 2022-06-08 at 13 59 49@2x" src="https://user-images.githubusercontent.com/88118603/172695968-32daf2d3-cef9-4526-894d-1f7e05b512a2.png">

**Comment by PhiDung-hub** [comment]
Hi, is there any solution for this issue?
