### ISSUE TITLE
`useMDXComponent` does not allow accessing named exports

### ISSUE THREAD

**Issue by stefanprobst** [contentlayerdev/contentlayer#246]
in MDX it is possible to [export arbitrary data as named exports](https://mdxjs.com/docs/what-is-mdx/#esm). these can be added by user-authored content, or by a plugin.

example:

```mdx
# Heading

Hello, world!

export const metadata = { key:'value' }
```

currently, `useMDXComponent` [only allows accessing the `default` export](https://github.com/contentlayerdev/contentlayer/blob/a560ae9cef2e658813e16ca6cf560633d543a2b3/packages/next-contentlayer/src/hooks/useMDXComponent.ts#L19) (which always is the React component), but there is no way to access the named exports.

**Comment by reubn** [comment]
This issue is stopping me from adopting Contentlayer

**Comment by stefanprobst** [comment]
> This issue is stopping me from adopting Contentlayer

you could try with something like:

```js
import React, { useMemo } from "react";
import ReactDOM from "react-dom";
import * as _jsx_runtime from "react/jsx-runtime";

function useMDXComponent(code) {
  return useMemo(() => {
    const scope = { React, ReactDOM, _jsx_runtime };
    const fn = new Function(...Object.keys(scope), code);
    return fn(...Object.values(scope));
  }, [code]);
}

function MyPage(props) {
  const { default: Content, ...data } = useMDXComponent(props.post.code)

  return (
    <main>
      <Content />
      <pre>{JSON.stringify(data, null, 2)}</pre>}
    </main>
  )
}
```

**Comment by reubn** [comment]
Great!

**Comment by schickling** [comment]
I agree with the underlying problem (i.e. feature gap). My current idea to address this would be to let the user specify the expected `export const myField = ...` fields as actual [document fields](https://www.contentlayer.dev/docs/reference/source-files/field-types).

Would this approach sufficiently address your use case?

**Comment by schickling** [comment]
Closing in favour of #64
