### ISSUE TITLE
don't generate invalid typescript

### ISSUE THREAD

**Issue by stefanprobst** [contentlayerdev/contentlayer#253]
`contentlayer` generates `export type * from './types'` [here](https://github.com/contentlayerdev/contentlayer/blob/aa4a7d045be33518fd62e9accebd65a57250e4c6/packages/%40contentlayer/core/src/generation/generate-dotpkg.ts#L372) which, surprisingly, is not valid typescript.

[TS playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcBUcBmUIFs4DkAdAPRIoDOBQA) says "Only named exports may use 'export type'."

**Comment by wrthwhl** [comment]
@schickling Thanks for the fix. And sorry for not responding to your request - I was taking a break.
