### ISSUE TITLE
Accessing markdown transformed by remark plugin

### ISSUE THREAD

**Issue by sarimabbas** [contentlayerdev/contentlayer#256]
Hello! Thank you for your work on this library!

I have a custom remark plugin that transforms markdown by modifying local image links. I notice the transformation is propagated to `document.body.html`, but does not appear in `document.body.raw`. Is it possible to also have a new property available e.g. `document.body.markdown` which has the transformed markdown string? Or is there another way to get access to it? Thank you so much!

**Comment by stefanprobst** [comment]
afaik `body.raw` will always point to the original file content - what's your usecase for having both html and markdown output?
