### ISSUE TITLE
MDX components  are cached and do not live reload

### ISSUE THREAD

**Issue by ivan-kleshnin** [contentlayerdev/contentlayer#260]
Hi! Thank you for this amazing library. The integration complexity you resolve here must be insane 🤯 so I hesitate to even raise this issue for a "beta" product.

--

Still, if you don't mind, I have noticed issues with components inside MDX content.

1. Despite what docs mention `components` props in `const MDXContent = useMDXComponent(home.body.code)` seem to have no effect:

```
<MDXContent />
behaves the same as
<MDXContent components={{MyButton}}/>
```

Instead of that `import` statements are required inside `.mdx` files or otherwise build fails immediately. 

```
---
title: xxx
---

import {MyButton} from "components" 

<MyButton/>
```

The necessity of mdx-content level imports  isn't mentioned in docs and, given there're different flavours of MDX, it's not clear what we should do. Comparing a `components` prop vs an `import` statement which seem to serve the same purpose: do we need one of them, which one, or both? 🤔 

2. Components used inside MDX seem to be heavily cached. 

If I change **`.mdx` body**, e.g. duplicate `<MyButton>` – it's reflected in the browser immediately.

However, if I change the **implementation**, the code at `components/MyButton.jsx` – it's not applied even if I restart a server. It's cached "forever" and refreshes only after I `rm -rf .contentlayer` folder.

Not sure if there's a bug or docs are incomplete or I miss something.
I'm simply following the docs at https://www.contentlayer.dev/docs/sources/files/mdx – nothing fancy.

**Comment by stefanprobst** [comment]
ad (1): this seems to be working just fine for me, check out [this example repo](https://github.com/stefanprobst/issue-contentlayer-mdx-components) for what i tried

**Comment by ivan-kleshnin** [comment]
Yes, thank you. I rechecked each difference and there were none. And now it works in my original repo as well. 
So I guess it was some temporary glitch.
