### ISSUE TITLE
failure (and poor error message) if `fields` is missing from `defineDocument`

### ISSUE THREAD

**Issue by timfee** [contentlayerdev/contentlayer#268]
Hi there,

Just came across a discrepancy with the docs vs. functionality.

I was creating a singleton Homepage document:
```tsx
export const Home = defineDocumentType(() => ({
  name: 'Home',
  isSingleton: true,
  filePathPattern: `index.mdx`,
}))
```

But got a pretty cryptic error when spinning it up, prefaced by `This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here: https://github.com/contentlayerdev/contentlayer/issues`.

The documentation doesn't say that `fields` is required:

<img width="244" alt="Screen Shot 2022-07-12 at 14 18 14@2x" src="https://user-images.githubusercontent.com/3246342/178597111-7b6990f7-8dc7-4470-a98a-5505b8a8607b.png">

However, when I changed `contentlayer.config.js` to `.ts`, it complained that `fields` was missing, and I was able to resolve the issue pretty trivially: 

```tsx
export const Home = defineDocumentType(() => ({
  name: 'Home',
  isSingleton: true,
  filePathPattern: `index.mdx`,
  fields: []
}))
```

Not sure if the documentation (where it's optional) is the intended behavior, or if the code is functioning correctly and friendlier errors/clearer docs would be helpful, but sharing the discrepancy :)

**Comment by schickling** [comment]
This should be addressed with the [`0.2.7` release](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.2.7). 🎉
