### ISSUE TITLE
Output mdx filename for debugging

### ISSUE THREAD

**Issue by kouliavtsev** [contentlayerdev/contentlayer#276]
Errors like these are hard to debug since you don't know what file is causing the error.

<img width="713" alt="Screenshot 2022-07-29 at 09 14 03" src="https://user-images.githubusercontent.com/1392575/181707001-50af48ac-17c8-4cc3-afee-9ead4bf7061a.png">

**Comment by kouliavtsev** [comment]
Uhh... I have learned that there was another duplicate output below.

I was working with moving a lot of legacy files, so many errors prevented seeing the correct output.

**Comment by schickling** [comment]
In case there's still a problem with this that needs to be fixed/improved in Contentlayer, please provide a repro. Otherwise can this issue be closed?

**Comment by kouliavtsev** [comment]
@schickling Can be closed, thx!
