### ISSUE TITLE
Warning: Contentlayer might not work as expected on Windows. 

### ISSUE THREAD

**Issue by joshua-v-dev** [contentlayerdev/contentlayer#280]
╥
╠══╦══╗
║  ║  ║
║  ║  ╠─An interrupt was produced by #0.
║  ║  ║
║  ║  ▼
║  ║
║  ╠─An unchecked error was produced.
║  ║
║  ║ TypeError: Cannot convert undefined or null to object
║  ║     at Function.entries (<anonymous>)
║  ║     at getFieldDefEntries (file:///C:/Users/joshu/Apps/t3-trivia-app/node_modules/@contentlayer/source-files/src/schema/provideSchema.ts:119:19)
║  ║     at next (file:///C:/Users/joshu/Apps/t3-trivia-app/node_modules/@contentlayer/source-files/src/schema/provideSchema.ts:25:25)
║  ║     at Generator.next (<anonymous>)
║  ║     at ISuspend.factory (file:///C:/Users/joshu/Apps/t3-trivia-app/node_modules/@effect-ts/system/_src/Effect/gen.ts:135:28)
║  ║     at FiberContext.evaluateNow (file:///C:/Users/joshu/Apps/t3-trivia-app/node_modules/@effect-ts/system/_src/Fiber/context.ts:1173:51)
║  ║     at file:///C:/Users/joshu/Apps/t3-trivia-app/node_modules/@effect-ts/system/_src/Fiber/context.ts:576:33
║  ║     at file:///C:/Users/joshu/Apps/t3-trivia-app/node_modules/@effect-ts/system/_src/Support/Scheduler/index.ts:15:9
║  ║
║  ║ Fiber: #9 (started at: 2022-07-30T03:05:05.669Z) was supposed to continue to:
║  ║
║  ║   a future continuation at packages/@contentlayer/source-files/src/index.ts:104:19
║  ║
║  ║ Fiber: #9 (started at: 2022-07-30T03:05:05.669Z) Execution trace:
║  ║
║  ║   packages/@contentlayer/source-files/src/schema/provideSchema.ts:18:8
║  ║
║  ║ Fiber: #9 (started at: 2022-07-30T03:05:05.669Z) was spawned by:
║  ║
║  ║ Fiber: #0 (started at: 2022-07-30T03:05:05.296Z) was supposed to continue to:
║  ║
║  ║   a future continuation at packages/@contentlayer/core/src/generation/generate-dotpkg.ts:82:13   
║  ║
║  ║ Fiber: #0 (started at: 2022-07-30T03:05:05.296Z) Execution trace:
║  ║
║  ║   packages/@contentlayer/core/src/generation/generate-dotpkg.ts:78:16
║  ║   packages/next-contentlayer/src/plugin.ts:35:12
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:41:18
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:40:10
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:47:15
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:39:26
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:37:12
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:117:12
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:75:36
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:197:13
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:186:28
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:184:44
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:171:28
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:169:31
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:156:28
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:154:15
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:151:15
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:150:15
║  ║   packages/@contentlayer/core/src/cwd.ts:24:43
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:135:27
║  ║   packages/@contentlayer/core/src/getConfig/index.ts:122:10
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:118:12
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:121:14
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:70:15
║  ║   packages/@contentlayer/core/src/getConfig/esbuild.ts:69:10
║  ║
║  ║ Fiber: #0 (started at: 2022-07-30T03:05:05.296Z) was spawned by: <empty trace>
║  ▼
▼
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at makeSource ()

**Comment by GokhanCerk** [comment]
you should check out to the **next.config.js**.

try this
```
const { withContentlayer } = require("next-contentlayer");

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
}

module.exports = withContentlayer(nextConfig)
```
