### ISSUE TITLE
Support new image field to serve images from public/images

### ISSUE THREAD

**Issue by marcofranssen** [contentlayerdev/contentlayer#287]
Currently I'm serving my images from public/images. Which is kind of the way to do it with Next.js if you are not using contentlayer.

In my content I refer to those images using `/images/some-image.png`

This absolute url is basically working to serve my images from the public folder that holds the images.

It would be great if an absolute path (starting with `/`) would be default find the images in the `public` folder.

The current behavior in the `0.2.7` release is searching for those images in my users home folder.

```
"blog/my-blog-post.md" with field "coverImage: /images/my-image.png" failed with {
       "filePath": "/Users/marco/images/my-image.png",
       "_tag": "node.fs.FileNotFoundError"
```

Would appreciate some feedback before I'm going to modify all my content to have relative filePaths if this feature/improvement would be considered.

```diff
-coverImage: /images/my-image.png
+coverImage: ../../public/images/my-image.png
```

While doing so, I also get very weird filePaths, that also don't make sense to use when rendering the images on my pages:

```javascript
{
  filePath: '../public/images/my-image.png',
  relativeFilePath: '../../public/images/my-image.png',
  …
}
```

As a workaround I now also add a computed field that updates my coverImage with an `url` property.

```javascript
  coverImage: {
    type: "nested",
    of: CoverImage,
    resolve: (doc) => doc.coverImage.url = doc.coverImage.filePath.replace(/(\.\.\/)+(public)/, ""),
  },
```

Maybe it makes sense to introduce some contentlayer setting that allows to configure some rootPath for urls that start with `/` so people using something different than nextjs can also use it.

e.g.

```javascript
{
  findAbsoluteImagePathsIn: `./public`
}
```

**Comment by marcofranssen** [comment]
Any chance some of the recent releases already got some of this funtionality implemented? Haven't been following the project very closely lately, so kind if hoping something that could help me slipped in already.

**Comment by schickling** [comment]
https://github.com/contentlayerdev/contentlayer/releases/tag/v0.2.7 contained experimental support for `image` fields. Did you give this a try already?

**Comment by marcofranssen** [comment]
Yes that is exactly the thing I tried and logged this issue for. 

How do I refer to images in my public folder?

I have all links currently as /images/my-image.png etc.

This will look for the image in the public folder. However that doesn't work with this feature. It will fail it can't find the image as it looks in the wrong place.

**Comment by schickling** [comment]
I've added an example for you that hopefully illustrates the current `type: image` usage pattern. It's not ideal yet and still experimental but it hopefully is already useful for your use case.

https://github.com/contentlayerdev/contentlayer/tree/main/examples/next-images
