### ISSUE TITLE
Configure warnings to be errors and fail build

### ISSUE THREAD

**Issue by jonbri** [contentlayerdev/contentlayer#304]
In our app's front matter, if I forget a required field (in this case `pageType`) I get a helpful warning in the console when running a build:
```
Warning: Found 1 problems in 24 documents. 
└── Missing required fields for 1 documents. (Skipping documents) 
 • "components/button/tabs/history.mdx" is missing the following required fields:
       • pageType: enum 
```
Is there a way to turn this warning into an error? Would like to fail the build in this case.

**Comment by schickling** [comment]
Yes. You can configure this via the `onMissingOrIncompatibleData` option in `makeSource`:

<img width="884" alt="CleanShot 2022-09-08 at 22 55 55@2x" src="https://user-images.githubusercontent.com/1567498/189224291-9b629dca-b437-4020-b877-f836f24bd0dd.png">
