### ISSUE TITLE
Module not found: Package path ./generated is not exported from package 

### ISSUE THREAD

**Issue by schwarzsky** [contentlayerdev/contentlayer#307]
I am facing issue in the title with get started example.

Created a repo in case you might wanna look, nextjs tries to fetch from package not from the folder `./contentlayer`.

https://github.com/schwarzsky/contentlayer-jsconfig-bug

**Comment by timlrx** [comment]
Your repo contains both `next.config.js` and `next.config.mjs`. Delete `next.config.js` and it will work :)

**Comment by schickling** [comment]
Thanks for helping out here @timlrx. 🙏 

@schwarzsky please leave a comment if this didn't help to resolve your issue.
