### ISSUE TITLE
Array functions do not work in `resolve` for `computedFields`

### ISSUE THREAD

**Issue by SandroMaglione** [contentlayerdev/contentlayer#315]
Hi,

When using array function (`map`, `join`, etc.) inside `resolve` I encounter an error.

In my app, I have the following configuration (minimal example to show the issue):
```ts
{
  ...
  computedFields: {
    title: {
      type: 'string',
      resolve: ({ translations }) => `Translations: ${translations.join(", ")}`
    },
  },
  fields: {
    translations: { type: 'list', required: true, of: { type: 'string' } },
  }
}
```

The `translations` value is correctly inferred as `string[]` by typescript, but then I get an error from contentlayer saying:
```shell
...  failed with TypeError: translations.join is not a function
```

This is the same if I use `map`.

Nonetheless, if instead I first use `split` (on a `string`) and then `join` on the resulting array, then **it works**.

May this be a bug in how contentlayer treats array?
> **Note**: If I try to print an array as a `string` the result is: `Chunk(...)`

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!
