### ISSUE TITLE
Cannot find module 'contentlayer/client' by running test with Jest

### ISSUE THREAD

**Issue by hawkup** [contentlayerdev/contentlayer#318]
I found this error when run jest for testing
```cmd
Cannot find module 'contentlayer/client' from '.contentlayer/generated/index.mjs'

Require stack:
  .contentlayer/generated/index.mjs
  pages/index.tsx
  __tests__/index.test.tsx
```

here is the codesandbox that fork next-contentlayer-example and setup Jest. you could run testing by `yarn test`
**codesandbox**: https://codesandbox.io/p/github/hawkup/next-contentlayer-example/draft/serene-wozniak
**repository**: https://github.com/hawkup/next-contentlayer-example/tree/draft/serene-wozniak

I already added this config on `jest.config.js` 
```js
{
	moduleNameMapper: {
	  "contentlayer/generated": "<rootDir>/.contentlayer/generated"
	}
}
```

**Comment by schickling** [comment]
Thanks a lot for reporting this. This seems to be one of (the many) rough edges of using Jest in a (partial) ESM setup. I usually recommend using [Vitest](https://vitest.dev/) as a more modern alternative but in case you (or others) are "stuck with Jest", I'd appreciate if someone from the community could help investigate this issue further.

**Comment by kouliavtsev** [comment]
@schickling @hawkup 

The issue can be fixed by updating `moduleNameMapper` in `jest.config.js`.

```
  moduleNameMapper: {
    "^contentlayer/generated": "<rootDir>/.contentlayer/generated",
    "^contentlayer/client": "<rootDir>/node_modules/contentlayer/dist/client",
    "^next-contentlayer/hooks":
      "<rootDir>/node_modules/next-contentlayer/dist/hooks",
  },
  transformIgnorePatterns: [
    "node_modules/(?!(contentlayer|next-contentlayer|@contentlayer)/)",
  ],
```

This works in Nextjs 12, yet fails in Nextjs 13. Investigating this a bit further.

> Thanks a lot for reporting this. This seems to be one of (the many) rough edges of using Jest in a (partial) ESM setup. I usually recommend using [Vitest](https://vitest.dev/) as a more modern alternative but in case you (or others) are "stuck with Jest", I'd appreciate if someone from the community could help investigate this issue further.

Vitest is great, yet for us it is not an option to rewrite all te tests.

**Comment by kouliavtsev** [comment]
@schickling @hawkup

After upgrading to Nextjs 13 I am getting this error.

<img width="1133" alt="Screenshot 2022-10-27 at 13 46 47" src="https://user-images.githubusercontent.com/1392575/198276174-683e9f00-bfd9-42e1-bb93-a538b15e0ced.png">

I am a bit confused why this is not being ignored anymore by the config above.

**Comment by kouliavtsev** [comment]
@hawkup The solution can be found in this PR.

https://github.com/vercel/next.js/issues/40183

@ThisIsMissEm Is working on [Improve Next Jest ESM support #41369](https://github.com/vercel/next.js/pull/41369)

@schickling I will try to open PR, to update the contentlayer docs.

**Comment by gustaveWPM** [comment]
> `@schickling @hawkup`
> 
> After upgrading to Nextjs 13 I am getting this error.
> 
> <img alt="Screenshot 2022-10-27 at 14 04 37" width="870" src="https://user-images.githubusercontent.com/1392575/198279645-29e11a6e-795a-41f2-8519-ddcb75088150.png">
> 
> I am a bit confused why this is not being ignored anymore by the config above.

Hello @kouliavtsev 
Sorry to awaken such an old issue, but... have you found any workaround? :)

Thank you in advance.

**Comment by cpatti97100** [comment]
up 🙏🏼 @kouliavtsev

**Comment by cpatti97100** [comment]
it seems like I can keep on going with this at least for now

```
// jest.config.js
moduleNameMapper: {
    'contentlayer/generated': '<rootDir>/.contentlayer/generated',
  },

// jest.testSetup.js
jest.mock('contentlayer/generated', () => {
  return {
    __esModule: true,
    allInstructionsForUses: [...]
  }
})

**Comment by gustaveWPM** [comment]
> it seems like I can keep on going with this at least for now
> 
> ```
> // jest.config.js
> moduleNameMapper: {
>     'contentlayer/generated': '<rootDir>/.contentlayer/generated',
>   },
> 
> // jest.testSetup.js
> jest.mock('contentlayer/generated', () => {
>   return {
>     __esModule: true,
>     allInstructionsForUses: [...]
>   }
> })
> ```

Oh, nice workaround haha.

Now I just use Vitest and abandoned Jest. Sorry, I can't help furthermore!
