### ISSUE TITLE
Next.js 13 support

### ISSUE THREAD

**Issue by mxkaske** [contentlayerdev/contentlayer#324]
Interestingly, upgrading `next@latest` in an existing `contentlayer` project will work. The reverse won't. That means, `create-next-app` first and `npm install contentlayer next-contentlayer` won't work as the peer dependency currently relies on `"^12"`.

https://github.com/contentlayerdev/contentlayer/blob/3e294cd1e85f72883edbda91aa67bcd699fb27ea/packages/next-contentlayer/package.json#L45

I'm not fully aware if that's the only bottleneck to make it run in Next 13.

Running contentlayer in the first version locally like below will work as expected. I convert the page the new `/app` directory into a Client Component with `"use client"` and use `"use"` instead to access the files.

```tsx
// /app/writing/[slug]/page.tsx
"use client";

import { use } from "react";
import { allPosts } from ".contentlayer/generated";

export async function generateStaticParams() {
  const posts = await allPosts;
  return posts.map((post) => ({
    slug: post.slug,
  }));
}

const getPost = async (slug: string) => {
  const post = allPosts.find((post) => post.slug === slug);
  return post;
};

export default function Post({ params }: { params: { slug: string } }) {
  const { slug } = params;
  const post = use(getPost(slug));
  return (
      <div
        dangerouslySetInnerHTML={{ __html: post.body.html }}
      />  
  );
}
```

Thanks to the new `use` function, accessing async data (server assess e.g.) can be done in components as well, not only pages. So we are not restricted on purely accessing the file(s) in a `page.tsx` Component. It can be accessed in **any** Client Components. 

Hope that helps!

**Comment by schickling** [comment]
This should be addressed with the [`0.2.9` release](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.2.9). 🎉

However, due to some blocking bugs in Next.js itself, React Server Components aren't yet supported. You can track the progress here: https://github.com/contentlayerdev/contentlayer/issues/311
