### ISSUE TITLE
Failed to compile after updating to v0.2.9

### ISSUE THREAD

**Issue by mflisikowski** [contentlayerdev/contentlayer#329]
Hi, I encountered such an error today after updating

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/1973631/200630645-7ae236fc-c6a7-4c02-b618-bd51e2af2fad.png">

Screen after update:

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/1973631/200631630-6e401b47-83fd-4f3b-b679-b8b17e258eeb.png">

Screen after downgrade:

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/1973631/200631957-14a573a8-155a-4754-920f-aa52d1e1e1bf.png">

_Originally posted by @mflisikowski in https://github.com/contentlayerdev/contentlayer/discussions/328#discussioncomment-4089059_

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!
