### ISSUE TITLE
"Hanging up"/No start with Next 13

### ISSUE THREAD

**Issue by lstephensca** [contentlayerdev/contentlayer#330]
So I have been trying to debug this for the better part of a day, and I am a bit lost. I installed the lts Next (with the app directory) and the contentlayer dependencies (following the example on the site), and it seemed to work for a moment. However, when I reran "yarn dev", I got the .contentlayer folder with only the cache and my terminal is stuck on the following screen:
![Screen Shot 2022-11-09 at 8 56 44 AM](https://user-images.githubusercontent.com/31998110/200949048-846bd171-83f2-4731-b45f-add461dcb34c.png)

I killed the command and reran yarn dev, but then I get:

![Screen Shot 2022-11-09 at 8 57 02 AM](https://user-images.githubusercontent.com/31998110/200949147-195f1444-8ddb-426d-a3ec-3001e381264d.png)

Nothing seems to be generated (other than the contentlayer cache), and the site is unreachable.

my contentlayer.config.ts:
```js
import { defineDocumentType, makeSource } from "contentlayer/source-files";

const Doc = defineDocumentType(() => ({
	name: "Doc",
	filePathPattern: "**/*.mdx",
	contentType: "mdx",
	fields: {
		title: { type: "string", required: true },
		description: { type: "string", required: true },
		isPublished: { type: "boolean", required: true },
	},
	computedFields: {
		url: {
			type: "string",
			resolve: (doc) => `/docs/${doc._raw.flattenedPath}`,
		},
	},
}));

export default makeSource({
	contentDirPath: "content",
	documentTypes: [Doc],
});
```

tsconfig.json:
```json
{
	"compilerOptions": {
		"target": "es5",
		"lib": ["dom", "dom.iterable", "esnext"],
		"allowJs": true,
		"skipLibCheck": true,
		"strict": true,
		"forceConsistentCasingInFileNames": true,
		"noEmit": true,
		"esModuleInterop": true,
		"module": "esnext",
		"moduleResolution": "node",
		"resolveJsonModule": true,
		"isolatedModules": true,
		"jsx": "preserve",
		"incremental": true,
		"baseUrl": ".",
		"paths": {
			"@/styles/*": ["src/styles/*"],
			"contentlayer/generated": ["./.contentlayer/generated"]
		},
		"plugins": [
			{
				"name": "next"
			}
		]
	},
	"include": [
		"next-env.d.ts",
		"**/*.ts",
		"**/*.tsx",
		".next/types/**/*.ts",
		".contentlayer/generated"
	],
	"exclude": ["node_modules"]
}
```
I probably have missed something important, but for the life of me I can not get it working. I ran into the same issue when I cloned the example next demo as well on Nextjs 13.0.2 with contentlayer 0.2.9 on node 16.18.0 (on mac). I ditched the beta app structure and just went with src/* and a content folder at the root, but I ran into the same issue. 

When it did run, it seemed to be very slow and took about a minute to finally get the dev server running. A fresh install sans contentlayer seemed to work just fine.

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

**Comment by lstephensca** [comment]
Well, I tried again this morning with the same results with yarn (1.22.19) and npm. However, when I loaded my example repo to [Stackblitz](https://stackblitz.com/github/lstephensca/next-cl?file=README.md) it seems to work just fine.

Steps taken:

- npx create-next-app next-cl --experimental-app
- npm i contentlayer next-contentlayer
- Configure next via documentation
- npm run dev

After some more poking around, I have found that the "export default makeSource" is where it seems to be hanging up in my dev environment. If I comment it out next dev seems to proceed, but as soon as I set "contentDirPath" it completely hangs up after creating 2 files in the .contentlayer cache directory.

**Comment by lstephensca** [comment]
So I finally got this working when I downgraded to 0.2.8 for contentlayer with a fresh install of Next 13 with the beta app structure. I do apologize for keeping this going/open. I just wanted to let everyone know what got it working in my case.

**Comment by schickling** [comment]
So you figured it out and this issue can be closed?

**Comment by lstephensca** [comment]
Yep! I appreciate the quick responses!
