### ISSUE TITLE
fountain support or ability to add support for developers

### ISSUE THREAD

**Issue by vanceingalls** [contentlayerdev/contentlayer#346]
i was reading through the docs to determine if it is possible to create an interpreter for arbitrary file types. I want to parse fountain files but learned that this isn't possible. Not sure if it helps but I did find this fork of fountain.js which attempts to parse the input as JSON https://github.com/mattdaly/Fountain.js/pull/18/commits/25053d71a1da73e4db0448a60d6cc3e751393501?diff=unified&w=1

**Comment by schickling** [comment]
Hi @vanceingalls. Thanks a lot for opening this issue. Unfortunately this isn't possible yet but shouldn't be too hard to accomplish. Feel free to open a PR adding this feature (ideally in a general way) or once there's more popular demand for this feature request, I'll consider adding support for this myself.
