### ISSUE TITLE
Alias connection in fields

### ISSUE THREAD

**Issue by henniaufmrenni** [contentlayerdev/contentlayer#35]
I've setup Contentlayer with [Fuse.js](https://fusejs.io/) to have simple yet effective fuzzy. For this I'm creating lists for Fuse.js  with `allDocuments` from Contentlayer. My content types have however different "titles", eg. for posts `title` and for people `name`. These document titles are what I present in the search results. In order to do this with just `allDocuments` and not having to import all content types and doing mutations on the different arrays (which does not seem ideal for maintainability), I've simply set up a second frontmatter field on some content types, so that all of them have for example `title` as a field, but that's a bit a hassle when working with content written by others. That's why it would be great  if there was an option in Contentlayer to create an alias, perhaps similar to how defaults are declared. 

Perhaps something like this:
```
  fields: {
    name: { type: 'string', required: true },
    title: { type: 'string', alias: 'name' }
  }
```

**Comment by schickling** [comment]
You can already do this with `computedFields`:

```ts
fields: {
    name: { type: 'string', required: true },
},
computedFields: {
    title: { type: 'string', resolve: _ => _.name }
}
```

(Note that this has a slight downside since you're duplicating the value and therefore slightly increase the JSON size.)

Please let me know if this works for you so we can close this issue.

**Comment by henniaufmrenni** [comment]
Yes that work's perfectly, thank you.
