### ISSUE TITLE
StackBlitz example not working?

### ISSUE THREAD

**Issue by pomber** [contentlayerdev/contentlayer#351]
When I try the StackBlitz example, either embedded or in stackblitz.com it doesn't load. Looks like a memory issue.

Embedded:
![image](https://user-images.githubusercontent.com/1911623/212651390-991b01c8-92f0-4b43-b179-7e8eb6825a68.png)

stackblitz.com:
![image](https://user-images.githubusercontent.com/1911623/212651560-7ba0d2f9-16e6-4b9b-a206-73f1429c46fc.png)

Tried Chrome and Firefox.

Not sure if it's just me (I also tried [this](https://developer.stackblitz.com/codeflow/working-in-codeflow-ide#out-of-memory-error))

**Comment by schickling** [comment]
Interesting. It seems to work for me. 🤔 

<img width="1535" alt="CleanShot 2023-01-16 at 15 11 55@2x" src="https://user-images.githubusercontent.com/1567498/212697989-628eb4ae-96db-4def-af01-3879263b8a6d.png">

**Comment by EricSimons** [comment]
@pomber hey! It looks like you might be running out of either browser and/or device memory 🤔 Could you click the "file an issue" button at the bottom of the stackblitz editor? That will include detailed info about your browser, memory, etc that should help us investigate this further

**Comment by schickling** [comment]
Assuming this problem has nothing to do with Contentlayer but rather with Stackblitz, I'm closing this issue. Please let me know if you think this is actually a problem with Contentlayer and I'll re-open the issue.

**Comment by pomber** [comment]
> @pomber hey! It looks like you might be running out of either browser and/or device memory 🤔 Could you click the "file an issue" button at the bottom of the stackblitz editor? That will include detailed info about your browser, memory, etc that should help us investigate this further

Done https://github.com/stackblitz/webcontainer-core/issues/943. I think the problem is with Windows/Chrome.
