### ISSUE TITLE
Not working with Turbopack 

### ISSUE THREAD

**Issue by madhavdutta** [contentlayerdev/contentlayer#364]
Hey anybody tried with `yarn dev --turbo`  ? It's working fine with webpack but giving errors with turbopack. Please help.

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

**Comment by madhavdutta** [comment]
I just created a new NextJS 13 project using npx create-next-app contentlayer-example

Followed all steps mentioned on this page https://www.contentlayer.dev/docs/getting-started

when I run the project using yarn dev --turbo it returns error but it works fine with yarn dev 

Please follow this page https://turbo.build/pack

Madhav

**Comment by nkilm** [comment]
@madhavdutta Are you getting the same error as I'm getting below?

![image](https://user-images.githubusercontent.com/79012023/217056118-73da3d0a-93bc-4c6e-866f-54798aadeff2.png)

#### I'm completely fine with `yarn dev` for now, since `turbo` is still in alpha.

**Comment by madhavdutta** [comment]
Thanks @nkilm but I think you did not understand the issue. I never said I am getting error with 'yarn dev' 
The whole issue is occurring with turbo pack. As Team Varcal is working on turbo pack and claiming it to be 5-6 times faster than normal webpack deployment. I am using contentlayer for my product and it's not working with --turbo pack . Let me attach the screenshot.

<img width="850" alt="Screen Shot 2023-02-07 at 12 30 12 AM" src="https://user-images.githubusercontent.com/5016004/217062415-4c2717cd-8cf3-497d-b1a2-819a29600337.png">

**Comment by git-no** [comment]
@madhavdutta I do work with Turborepo and PNPM and it works, very fast.

**Comment by mkalsi25** [comment]
`Turbopack` is still in **_beta_**. It would be really better if we wait for **_stable_** version.

However if someone want to use it, they can use it with some modification in files like `tsconfig.config.ts`, `next.config.js`, `package.json`.

when we use Turbopack, it doesn't generate our Contentlayer automatically. In order to generate Contentlayer, I edited files like this

```
// package.json
"scripts": {
    "dev": "contentlayer dev && next dev --turbo",
    "build": "contentlayer build && next build",
    "start": "next start"
  },
```

```
// tsconfig.js
"baseUrl": ".",
    "paths": {
      "contentlayer/generated": [".contentlayer/generated"]
    },

```

`// next.config.js`
Remove `withContentlayer` function because it doesn't work with turbopack which is why we use their CLI in package.json but It can be solve in future using some more customizations once stable version of turbopack is released.



Here's screenshot, It works for me
<img width="2235" alt="Screenshot 2023-05-12 at 11 12 15 PM" src="https://github.com/contentlayerdev/contentlayer/assets/68652559/85c559cb-c74e-4ca5-ae67-84a06a16c814">

Feel free to ask if you have question.

**Comment by fiik346** [comment]
when i run `pnpm dev`, it's just run `contentlayer dev`. So, how to run contentlayer and next in same time, but just in one command?



> `Turbopack` is still in **_beta_**. It would be really better if we wait for **_stable_** version.
> 
> However if someone want to use it, they can use it with some modification in files like `tsconfig.config.ts`, `next.config.js`, `package.json`.
> 
> when we use Turbopack, it doesn't generate our Contentlayer automatically. In order to generate Contentlayer, I edited files like this
> 
> ```
> // package.json
> "scripts": {
>     "dev": "contentlayer dev && next dev --turbo",
>     "build": "contentlayer build && next build",
>     "start": "next start"
>   },
> ```
> 
> ```
> // tsconfig.js
> "baseUrl": ".",
>     "paths": {
>       "contentlayer/generated": [".contentlayer/generated"]
>     },
> ```
> 
> `// next.config.js` Remove `withContentlayer` function because it doesn't work with turbopack which is why we use their CLI in package.json but It can be solve in future using some more customizations once stable version of turbopack is released.
> 
> Here's screenshot, It works for me <img alt="Screenshot 2023-05-12 at 11 12 15 PM" width="2000" src="https://user-images.githubusercontent.com/68652559/238043177-85c559cb-c74e-4ca5-ae67-84a06a16c814.png">
> 
> Feel free to ask if you have question.

**Comment by mkalsi25** [comment]
> when i run `pnpm dev`, it's just run `contentlayer dev`. So, how to run contentlayer and next in same time, but just in one command?
> 
> > `Turbopack` is still in **_beta_**. It would be really better if we wait for **_stable_** version.
> > However if someone want to use it, they can use it with some modification in files like `tsconfig.config.ts`, `next.config.js`, `package.json`.
> > when we use Turbopack, it doesn't generate our Contentlayer automatically. In order to generate Contentlayer, I edited files like this
> > ```
> > // package.json
> > "scripts": {
> >     "dev": "contentlayer dev && next dev --turbo",
> >     "build": "contentlayer build && next build",
> >     "start": "next start"
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > // tsconfig.js
> > "baseUrl": ".",
> >     "paths": {
> >       "contentlayer/generated": [".contentlayer/generated"]
> >     },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `// next.config.js` Remove `withContentlayer` function because it doesn't work with turbopack which is why we use their CLI in package.json but It can be solve in future using some more customizations once stable version of turbopack is released.
> > Here's screenshot, It works for me <img alt="Screenshot 2023-05-12 at 11 12 15 PM" width="2000" src="https://user-images.githubusercontent.com/68652559/238043177-85c559cb-c74e-4ca5-ae67-84a06a16c814.png">
> > Feel free to ask if you have question.

Try use [concurrently](https://github.com/open-cli-tools/concurrently). 

`
..
dev: "concurrently \"contentlayer dev\" \"next dev --turbo\""
..
`
