### ISSUE TITLE
imagescript dependency has an AGPL License.

### ISSUE THREAD

**Issue by mikayla-maki** [contentlayerdev/contentlayer#368]
Here was the usage of imagescript that I could find:

https://github.com/contentlayerdev/contentlayer/blob/main/packages/%40contentlayer/source-files/src/fetchData/mapping/field-image.ts#L97-L126

Note the license of this dependency here:

https://github.com/matmen/ImageScript/blob/master/LICENSE

I'm unsure if this is actually an issue for y'all, but I couldn't see any discussion of the license in the closed issues so I thought I'd open one now for posterity :)

**Comment by LunaticMuch** [comment]
I actually agree with this - it's a problem in many situations

**Comment by nicholasgriffintn** [comment]
It would be good to get this resolved as it is a copyleft license which makes the use of contentlayer restricted somewhat.

**Comment by matmen** [comment]
FWIW, ImageScript switched to a dual-licensing model on 23-11-06: https://github.com/matmen/ImageScript/compare/140a93eb6e97ea63580b75c1ab51285e0d7ed04d...e4836a063a1041463f47131007d0be02b9c1c282
