### ISSUE TITLE
Module not found: Can't resolve 'file:/'

### ISSUE THREAD

**Issue by airtonix** [contentlayerdev/contentlayer#376]
```
https://nextjs.org/docs/messages/module-not-found
Could not find files for / in .next/build-manifest.json
Could not find files for / in .next/build-manifest.json
> Promise returned in next config. https://nextjs.org/docs/messages/promise-in-next-config
wait  - compiling /_error (client and server)...
error - ./node_modules/@contentlayer/core/dist/getConfig/index.js:69:0
Module not found: Can't resolve 'file:/'
```

Not sure how to make this go away.

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide **minimal** a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

**Comment by airtonix** [comment]
yep, one incoming now

**Comment by airtonix** [comment]
hurumph....

![sigh](https://user-images.githubusercontent.com/61225/218089790-7342f9aa-efad-4f71-a6f9-5f03fbd5721b.gif)

my bad...

Turns out when you try to import a thing that doesnt exist, this is what you get: 

```ts
import type {
  GalleryBlock,
  HeroBlock,
  SimpleBlock,
  VideoBlock,
  CtaBlock,
  CardBlock  // 🫲 did not exist
} from "contentlayer/generated";
```

**Comment by AhmadNasrHosna** [comment]
@airtonix 
How did you fix the issue?
I'm stuck with this error

> Cannot find module 'contentlayer/generated' or its corresponding type declarations.ts(2307)
