### ISSUE TITLE
What is the best way to write test with contentLayer

### ISSUE THREAD

**Issue by sergeunity** [contentlayerdev/contentlayer#382]
Hi all 

I'm pretty new in test world. But I'm improving myself and I want to add test for my app. 

I read in an issue there, and you advise using vitest. 

I want to know what is the default config we need to be able to make is work. 

 I have 2 questions. 

1. **How I can tell to vitest where it can find the generated files ?**

I use  `import { allDocs } from "contentlayer/generated";` and I have this error
<img width="620" alt="image" src="https://user-images.githubusercontent.com/52750122/219685079-f100e33e-5f9f-4070-ae75-749b06dc8684.png">

2.  **Do we have tool to mockup generated files ? I want to test functions using allDocs. It is best practice to create a fake array or to generate the allDocs with fake md files ?**

**Comment by schickling** [comment]
I haven't tested this myself yet but you could give the `alias` feature of Vite a try or the [vite-tsconfig-paths](https://github.com/aleclarson/vite-tsconfig-paths#readme) plugin which picks up `paths` from your tsconfig.
