### ISSUE TITLE
Chinese mdx file name conversion problem

### ISSUE THREAD

**Issue by majiayu000** [contentlayerdev/contentlayer#385]
I'm usingContentlayer. My mdx file name contains chinexe

Such like  `python with 函数链.mdx`

after generate I got

`import blog__python__pythonWithMdx from './blog__python__python with 函数链.mdx.json' assert { type: 'json' }`

in _index.mjs

When I create two file named like `python with 函数链.mdx` and `python with 函数.mdx`  error comes 
```
import blog__python__pythonWithMdx from './blog__python__python with 函数链.mdx.json' assert { type: 'json' }
import blog__python__pythonWithMdx from './blog__python__python with 函数.mdx.json' assert { type: 'json' }
```

I check source code find question maybe in https://github.com/contentlayerdev/contentlayer/blob/ad462a4126d33851fde012ef072bff4cffef0d06/packages/%40contentlayer/core/src/generation/generate-dotpkg.ts#L322

But I am new to ts, dont konw how to do

**Comment by nkilm** [comment]
@majiayu000 Related to #375 and #337

**Comment by schickling** [comment]
Thanks @nkilm. Closing as duplicate.
