### ISSUE TITLE
relative imports of MDX assets not work

### ISSUE THREAD

**Issue by hutuyishi** [contentlayerdev/contentlayer#387]
sorry  my english is not good

# issue info 
my issue like this https://github.com/contentlayerdev/contentlayer/issues/266

![image](https://user-images.githubusercontent.com/104620424/221394706-6f384379-d34c-4bf4-ac63-e9f2414c5861.png)

i want to import the `C1` component  in the `index.mdx`

but it not work

# error info
 
![image](https://user-images.githubusercontent.com/104620424/221394942-bf886f57-d132-492a-8043-de3569949427.png)

i open the url `http://localhost:3000/posts/a22`  , i have see nothing 
 
# my code
here is my code  https://github.com/hu-tu-yi-shi/tmp-contentlayer-bug

 

can you help me  , thank you very much

**Comment by nkilm** [comment]
@hu-tu-yi-shi Generally we don't import & use the components that way. We use [useMDXComponent](https://www.contentlayer.dev/docs/sources/files/mdx#usage-from-nextjs) hook to process the `.mdx` files and use custom components. 


## Example

```typescript
// https://www.contentlayer.dev/docs/sources/files/mdx#usage-from-nextjs

import React from 'react'
import { allPosts, type Post } from 'contentlayer/generated'
import { useMDXComponent } from 'next-contentlayer/hooks'

export const getStaticProps = () => {
  const post = allPosts[0]
  return { props: { post } }
}

const MyButton: React.FC = () => <button>Click me</button>

const Page: React.FC<{ post }> = ({ post }) => {
  const MDXContent = useMDXComponent(post.body.code)
  
  return (
    <div>
      {/* Some code ... */}
		// MyButton is the custom component which can be used in .mdx file
      <MDXContent components={{ MyButton }} />
    </div>
  )
}

export default Page
```

**Comment by hutuyishi** [comment]
same  https://github.com/contentlayerdev/contentlayer/issues/11
