### ISSUE TITLE
Cannot find module 'contentlayer/generated'

### ISSUE THREAD

**Issue by SuperStephenProMax** [contentlayerdev/contentlayer#392]
```
node version 16.19.1
system: macos 13.2.1
```

exection steps:

```
npx create-next-app@latest --experimental-app
✔ What is your project named? … next-boilerplate
✔ Would you like to use TypeScript with this project? … No / Yes
✔ Would you like to use ESLint with this project? … No / Yes
✔ Would you like to use `src/` directory with this project? … No / Yes
✔ What import alias would you like configured? … @/*
```

Execute according to this document: https://www.contentlayer.dev/docs/getting-started

This is the demo link: https://github.com/SuperStephenProMax/next-boilerplate

in `app/page.tsx ` file
in first line: `import { allPosts } from 'contentlayer/generated';` has error: Cannot find module 'contentlayer/generated'
link: https://github.com/SuperStephenProMax/next-boilerplate/blob/25c19b124f7a1d956cfa3f13db068c8ecc2eee67/app/page.tsx#L1

**Comment by git-no** [comment]
@SuperStephenProMax Have you ever build the app, meaning does your `.contentlayer/generated` exists?

**Comment by SuperStephenProMax** [comment]
Thanks, I tried it and it works.
