### ISSUE TITLE
When the .contentlayer is not automatically generated after installation

### ISSUE THREAD

**Issue by liuliuliucome** [contentlayerdev/contentlayer#410]
When the .contentlayer is not automatically generated after installation

<img width="291" alt="image" src="https://user-images.githubusercontent.com/4387324/230000932-4db1e8a0-afd9-4432-90e4-1cb9c0b255c2.png">

**Comment by cibulka** [comment]
Possible duplicate of https://github.com/contentlayerdev/contentlayer/issues/415
