### ISSUE TITLE
Cannot use "export" feature of Nextjs with current ContentLayer config

### ISSUE THREAD

**Issue by ashiishme** [contentlayerdev/contentlayer#426]
Hi team,

I was trying to setup Contentlayer to manage my posts content using the experimental `app` directory which now supports the [static export](https://beta.nextjs.org/docs/configuring/static-export).

The below config is required to support the export:
```
const nextConfig = {
 ...
  output: "export",
}
```

And the **Contentlayer** uses `redirect` property to hook into the application.

As state by the Nextjs, that the `redirect` [config is not required](https://nextjs.org/docs/messages/export-no-custom-routes) for the static export. The application is failing.

And, I cannot use the Contentlayer for static export.

**Is there any workaround to this?**

**To reproduce**

- Create a new Nextjs application and setup Contentlayer
- Setup the `next.config.js` file to use Contentlayer config
- Set `output:"export"` in your config
- Run the application

**Comment by schickling** [comment]
This should be addressed with the [`0.3.2` release](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.3.2). 🎉
