### ISSUE TITLE
Error when using components that have props in MDX

### ISSUE THREAD

**Issue by spcbfr** [contentlayerdev/contentlayer#434]
I have a component called `callout` it requires two props, a `title` and a `prop`. I have this component listed as a value for the `components` prop in the `MDXcontent` component as in: `<MDXContent components={{callout}}/>`. I then go on to use it in a few mdx posts. those posts after updating the next & contentlayer packages to the latest version have been getting this error:

`cannot access .proptypes on the server. you cannot dot into a client module from a server component. you can only pass the imported name through.`

if I go and remove the component from the affected pages, the page loads normally.

for context I am using the app directory in nextjs and of course React Server Components

**Comment by schickling** [comment]
Sorry for the late response and thanks for opening this issue. Can you please provide **minimal** a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

**Comment by spcbfr** [comment]
[my blog](https://github.com/spcbfr/nextjs-blog) is pretty minimal itself, the thing is I solved the problem by making the page that includes the MDX rendering component into a client page with "use client" which is weird because you guys added support for server components a few weeks ago.

Here is the [commit](https://github.com/spcbfr/nextjs-blog/commit/2de9cb7ec8ad269dfcff0ffe9c1f78aec6f1b71e) where I fixed the issue. as you can see I added the `"use client"` directive to the MDX component page and then I was able to use nested components normally

**Comment by rileyKacmarynski** [comment]
Had this same issue. Updating to next `13.4.8.canary.5` fixed it.
