### ISSUE TITLE
Installing contentlayer with pnpm requires markdown-wasm

### ISSUE THREAD

**Issue by anonrig** [contentlayerdev/contentlayer#435]
It fails without installing `markdown-wasm` on pnpm.

**Comment by trevorpfiz** [comment]
I was having similar issues, but I switched from `next.config.mjs` to `next.config.js` and things have been working smoother.

**Comment by DopamineDriven** [comment]
same for me but with using Yarn in a turborepo. Next or contentlayer should have a cli warning if either package detects next.config.mjs when using next-contentlayer and contentlayer since I've seen another thread about this issue elsewhere. 

Odd that we'd have to use commonjs

**Comment by dstroot** [comment]
Don't auto close - not stale and still an issue.

**Comment by anonrig** [comment]
...
