### ISSUE TITLE
Build fails on vercel however succeds on local

### ISSUE THREAD

**Issue by AkashRajpurohit** [contentlayerdev/contentlayer#44]
Running `yarn build` locally works fine, however on vercel the build fails with error

![image](https://user-images.githubusercontent.com/30044630/141607946-c585239e-d8e5-4498-a46e-943340fba044.png)

I feel this might be similar to the issue mentioned here #41 as it seems the build fails when type checking is done on vercel during compilation step.

**Comment by ipatate** [comment]
same problem

**Comment by lucas-homer** [comment]
same problem here too

**Comment by schickling** [comment]
I'll try to look into this soon. Just to confirm:

1. This doesn't happen locally even when having deleted `.next` and `node_modules/.contentlayer` before?
2. This happens consistently on every (re)build on Vercel?

**Comment by ipatate** [comment]
yes, after deleted ```node_modules/.contentlayer```, i have the same problem. It's strange, because i found a folder .contentlayer to the root on my project with an index ```export {}``` inside. I deleted this folder and now it's work localy. I push for deploy and bim, same error. 🧐

**Comment by schickling** [comment]
As a temporary workaround you can call `yarn contentlayer build` before `next build` in your CI step

**Comment by ipatate** [comment]
i tried before your message, same error. The documents are generated before build, it's not the problem apparently

**Comment by schickling** [comment]
@ipatate @lucas-homer can you please provide your Yarn/NPM and Node version?

**Comment by schickling** [comment]
I've released a new `dev` version (hopefully) containing a fix. Please get it a try so I cut a stable release for everyone. 🤞 

`yarn add contentlayer@dev next-contentlayer@dev`

**Comment by ipatate** [comment]
ok for me with dev version. Work on vercel now

**Comment by schickling** [comment]
Should be fixed now: https://github.com/contentlayerdev/contentlayer/releases/tag/v0.0.32

**Comment by dgknca** [comment]
@schickling this is happening again in v0.3.4.

**Comment by Bodrie** [comment]
Yep, same here, its complaining about not existing property, but it is actually there and the local build passes...

![265136206-869f0556-d5ca-4c27-86ab-db02628b11d1](https://github.com/contentlayerdev/contentlayer/assets/80153626/3fbbcf6b-a73f-4ca9-a8d3-e2b6aef115eb)
