### ISSUE TITLE
Error on next-contentlayer import of a named export from a CommonJS module

### ISSUE THREAD

**Issue by samjhecht** [contentlayerdev/contentlayer#440]
hi @schickling - I've run into a wall trying to work around this error: 

```
error - file:///Users/sam/code/irregular-expressions/node_modules/next-contentlayer/dist/hooks/useLiveReload.js:1
import { addMessageListener } from 'next/dist/client/dev/error-overlay/websocket.js';
         ^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'addMessageListener' not found. The requested module 'next/dist/client/dev/error-overlay/websocket.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'next/dist/client/dev/error-overlay/websocket.js';
const { addMessageListener } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5) {
  digest: undefined
}
```

It started rearing it's head after I migrated from material UI to chakra UI, but I haven't made changes to the way i'm leveraging contentlayer.   Here is one of the [slug].tsx pages that will trigger the error in dev: https://github.com/samjhecht/irregular-expressions/blob/chakra/pages/essays/%5Bslug%5D.tsx

It looks like this may well be related to this issue: https://github.com/contentlayerdev/contentlayer/issues/135.   is there a known option for avoiding this problem without making changes to the next-contentlayer module?  

Note: I was able to narrow this error down to useMDXComponent.   if I remove that from the page, it loads without the error.

**Comment by Pagebakers** [comment]
I had to patch this in `useLiveReload.js` to make it work.

```
import websocket from 'next/dist/client/dev/error-overlay/websocket.js';
const { addMessageListener } = websocket;
import router from 'next/router.js';
const { useRouter } = router;
```

**Comment by Forsto2012** [comment]
I get this same error on build in NextJS, but it works fine in dev.

**Comment by schickling** [comment]
@samjhecht I've given your repo a try. While I could reproduce the issue, the problem disappeared after upgrading to Next.js `13.4.4`. 

Generally I'd recommend switching over to the new RSC approach using the `app` dir instead of the `pages` dir if possible. If someone else is running into this issue, please leave a comment with a minimal reproduction repo.
