### ISSUE TITLE
terminal get frozen when running contentlayer command

### ISSUE THREAD

**Issue by Seokhyeon315** [contentlayerdev/contentlayer#461]
I have created a t3 stack project with the latest version and had set up with contentlayer.config.js file and made a sample mdx file and then when I run  `npm run dev` with package.json file including `"dev": "concurrently \"contentlayer dev\" \"next dev\"",
    "build": "contentlayer build && next build",`, then my terminal gets frozen. There are cache files are created on .contentlayer directory but nothing happened and even localhost is not opening after running these commands.

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide **minimal** a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

**Comment by Seokhyeon315** [comment]
@schickling I created a new public repository that includes the steps I did.
Here is a link: https://github.com/Seokhyeon315/test-contentlayer-t3stack 
Let me know what I did wrong or advice to fix this problem...

**Comment by mkalsi25** [comment]
Mate, I have a simple question for you.

Why are you using command line of `contenful` in dev script of `package.json` especially when already use `withContentlayer` in your NEXTJS configuration?

**Comment by Seokhyeon315** [comment]
@mkalsi25 I used `contentlayer dev` command to generate static data of mdx file so that I can use on client side of pages. However, even if I don't change the package.json file like just running `npm run dev ` or `npm run build`, the terminal still gets frozen. I am not sure if this occurs because contentlayer is optimized for the app directory of next js or if I set up something wrong.

**Comment by mkalsi25** [comment]
> @mkalsi25 I used `contentlayer dev` command to generate static data of mdx file so that I can use on client side of pages. However, even if I don't change the package.json file like just running `npm run dev ` or `npm run build`, the terminal still gets frozen. I am not sure if this occurs because contentlayer is optimized for the app directory of next js, or my mdx file includes Korean language or if I set up something wrong.

@Seokhyeon315  First of all, you need to remove `concurrently` and `contentlayer` from `package.json`
[https://github.com/Seokhyeon315/test-contentlayer-t3stack/blob/main/package.json#L6-L7](https://github.com/Seokhyeon315/test-contentlayer-t3stack/blob/main/package.json#L6-L7)

because `withContentLayer` function do all generation from mdx file to static data.
[https://github.com/Seokhyeon315/test-contentlayer-t3stack/blob/main/next.config.mjs#L14](https://github.com/Seokhyeon315/test-contentlayer-t3stack/blob/main/next.config.mjs#L14)

and test it after modify above changes.

**Comment by Seokhyeon315** [comment]
@mkalsi25  As you said, I remove `concurrently` and `contentlayer` from package.json. And I run `npm run dev`, then my terminal stopped at this: 
<img width="662" alt="image" src="https://github.com/contentlayerdev/contentlayer/assets/72924651/762513ee-b96e-41e5-90bc-14e723b49088">

**Comment by mkalsi25** [comment]
> @mkalsi25 As you said, I remove `concurrently` and `contentlayer` from package.json. And I run `npm run dev`, then my terminal stopped at this: <img alt="image" width="662" src="https://user-images.githubusercontent.com/72924651/241576538-762513ee-b96e-41e5-90bc-14e723b49088.png">
> 
> Same as when I run `npm run build`: <img alt="image" width="659" src="https://user-images.githubusercontent.com/72924651/241576810-6521d661-1dbf-4fe0-8d3c-59e82463edf4.png"> and even my `Ctrl+C` is not working at this point.

did you open browser with `http://localhost:3000 `after running `npm run dev`.

**Comment by Seokhyeon315** [comment]
No, I didn't. I was just waiting after I run `npm run dev` and remained like the screenshot and the laptop gets hot. I am using M1 macbook pro and terminal frozen situation never happened before... I might be asking dumb questions but since I am kinda new to this stuff like contentlayer so I want to fix this problem. 🥲

**Comment by mkalsi25** [comment]
I tested on my computer. It works fine on terminal and browser with both `build` and `dev`.

so, please test it with opening `http://localhost:3000` on browser, don't wait for terminal. 🥂

**Comment by danton-ten-six** [comment]
I have been having this problem as well for the last few days. When I run dev on the MacOS terminal (zsh), it stops out with "Contentlayer config change detected. Updating type definitions and data...".

However, no issues when running dev in the VSCode terminal. Perhaps it is a permissions issue when generating the contentlayer files?
Similar problem to Issue 330 (https://github.com/contentlayerdev/contentlayer/issues/330).

**Comment by Stephane-Pires** [comment]
> I have been having this problem as well for the last few days. When I run dev on the MacOS terminal (zsh), it stops out with "Contentlayer config change detected. Updating type definitions and data...".
> 
> However, no issues when running dev in the VSCode terminal. Perhaps it is a permissions issue when generating the contentlayer files? Similar problem to Issue 330 (#330).

Running my project in VsCode terminal worked. 👍 Congrats

**Comment by Seokhyeon315** [comment]
When I tried this, I only used iterm2 terminal on macOS, not vscode terminal. Maybe that's the reason of the problem but my opinion is it shouldn't be happening whatever terminal we use when trying to integrate contentlayer with other frameworks.

**Comment by wilstaley** [comment]
> I have been having this problem as well for the last few days. When I run dev on the MacOS terminal (zsh), it stops out with "Contentlayer config change detected. Updating type definitions and data...".
> 
> However, no issues when running dev in the VSCode terminal. Perhaps it is a permissions issue when generating the contentlayer files? Similar problem to Issue 330 (#330).

I followed the getting started guide exactly and am experiencing this same issue.  Totally frozen when running from MacOS terminal.

**Comment by Seokhyeon315** [comment]
So the only solution is just to run commands on VS Code terminal, I guess...
But, I wish if contentlayer team can fix this problem to make it not get frozen on iterm2.

**Comment by schickling** [comment]
I'd be happy to try to address this issue once we've identified the underlaying problem. Would be great if someone could help with investigating the root problem! 🙏

**Comment by danton-ten-six** [comment]
> I'd be happy to try to address this issue once we've identified the underlaying problem. Would be great if someone could help with investigating the root problem! 🙏

I'm happy to help however I can - but I still can't figure out the underlying issue. Code works in the VSCode integrated terminal (zsh and bash), but not not in Terminal.app (zsh) or iTerm2.

**Comment by Seokhyeon315** [comment]
@schickling Has this issue fixed yet?

**Comment by andrei-zgirvaci** [comment]
This issue hasn't been fixed.
