### ISSUE TITLE
Cannot use useMDXComponent to generate component.

### ISSUE THREAD

**Issue by KaiHiwatari8** [contentlayerdev/contentlayer#463]
I am trying to create a blog website for my pet project. I am using contentlayer to handle the blog page content. However, I am running into an error when generating the component from my .mdx files. Please find the complete details below.

Issue Type: Error
Error level: Blocker
Code that is causing trouble: `useMDXComponent from "next-contentlayer/hooks"`
Content file type: MDX
Version log:
- `next`: `^13.4.2`
- `next-contentlayer`: `^0.3.2`
- `contentlayer`: `^0.3.1`
Link to the troublesome line: [here](https://github.com/KaiHiwatari8/tennessee/blob/master/app/(marketing)/plans/%5Bpath%5D/page.tsx#L32)
Link to contentlayer.config.ts: [here](https://github.com/KaiHiwatari8/tennessee/blob/master/contentlayer.config.ts)
Link to repository: [here](https://github.com/KaiHiwatari8/tennessee)

Error: 
<img width="1193" alt="Screenshot 2023-05-25 at 6 50 32 PM" src="https://github.com/contentlayerdev/contentlayer/assets/47256627/0df26d52-d4d3-4e31-8974-8bc07b0df012">

Please advise!

**Comment by schickling** [comment]
Thanks a lot @KaiHiwatari8. To make it easier for me to investigate (and potentially fix) the problem, would you please mind minimizing the repository as much as possible? :pra

**Comment by jjmountain** [comment]
Experiencing same issue here as @KaiHiwatari8 with

`next`: `13.4.4`
`next-contentlayer`: `^0.3.2`
`content-layer`: `^0.3.2`

Previously I was fixing it by using `getMDXComponent` hook instead but this leads to the following. Note that `use client` cannot be used in this page as we are using server side functions here.

<img width="956" alt="Screenshot 2023-05-27 at 1 09 20" src="https://github.com/contentlayerdev/contentlayer/assets/21108437/23d44a30-71b3-46d8-b0fb-9d3b2879d7c3">

**Comment by mkalsi25** [comment]
I see what you are trying to do. You need to create new component with `use client` and import third party library component `getMDXComponent`. It will works for sure.

For more info, Take a look:  `https://nextjs.org/docs/getting-started/react-essentials#third-party-packages`

I hope you find your answers. 

_Happy Coding_. 👨🏻‍💻

**Comment by KaiHiwatari8** [comment]
@mkalsi25 Your suggestion worked. However, I did not use `use client` with my component and is working just fine. Thank you.

That being said, the issue I faced, is that a bug?

**Comment by schickling** [comment]
Thanks a lot for your help @mkalsi25!

@KaiHiwatari8 happy to take a look once you've confirmed there is a bug together with a **minimal** reproduction repo. 🙏

**Comment by mkalsi25** [comment]
I think, issue is already resolved. 😉 @schickling
