### ISSUE TITLE
useLiveReload() doesn't work with server components

### ISSUE THREAD

**Issue by altano** [contentlayerdev/contentlayer#468]
I'm trying to use contentlayer + mdx + Next.js 13 + react server components + live reload.

contentlayer + mdx + Next.js 13 + react server components works fine **without live reloading**. If I try to add the `useLiveReload()` hook to my server component I get the error:

> error createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component

The source of `useLiveReload` makes it clear it expects to be used as a client component. Is it possible to get contentlayer working with server components AND live reload?

**Comment by schickling** [comment]
Thanks for opening this issue. Can you please provide **minimal** a reproduction repo with instructions how to reproduce the problem you're experiencing? Thank you!

**Comment by altano** [comment]
@schickling do you by any chance know of any code sandbox type sites that would let me create a reproduction of the issue, one that works with next + contentlayer? Stackblitz prevents add-ons from being installed, so I can't install swc/next. Meanwhile codesandbox seems completely broken atm and I can't even install npm packages.

**Comment by CompuIves** [comment]
Hey @altano! Do you see errors atm on CodeSandbox? If you fork [this sandbox](https://codesandbox.io/p/sandbox/next-js-fxis37?file=/app/page.tsx:1,1) you should have a version running of Next.js that can have new dependencies.

**Comment by altano** [comment]
Mr. Codesandbox himself, cool. 

I was able to fork your sandbox and run `npm install @contentlayer/source-files@latest contentlayer@latest next-contentlayer@latest next@latest react@latest react-dom@latest`, so that unblocks me.

@CompuIves in [this sandbox](https://codesandbox.io/p/sandbox/nextjs-mdx-contentlayer-fq2sgp?file=%2Fpackage.json%3A1%2C1) I can't npm install, I either get errors from npm where packages and versions are undefined or I get EACCES errors. I submitted feedback. I can't make heads or tails of it.
<img width="1432" alt="image" src="https://github.com/contentlayerdev/contentlayer/assets/1009/592774f6-d845-4001-a50b-4e8dd9e4be5e">

**Comment by CompuIves** [comment]
Woh, that is very weird. It almost looks like this is a bug in npm? 🤔 

What does `yarn install` do, does that work?

**Comment by altano** [comment]
> What does `yarn install` do, does that work?

works perfectly, heh.

@schickling [here is a repro](https://codesandbox.io/p/sandbox/nextjs-mdx-contentlayer2-5dwf44?file=%2Fcontentlayer.config.ts%3A33%2C7) of `useLiveReload` not working in a server component. Click the "MDX Test Page" link You shouldn't really need it though, as the reason `useLiveReload` doesn't work in a server component is very straightforward: it uses a bunch of hooks that can't be used in server components, such as useEffect.

**Comment by schickling** [comment]
`useLiveReload` is indeed not intended to be used in React server components. Can you confirm the live-reload doesn't work when you remove the `useLiveReload` call?

**Comment by altano** [comment]
It _wasn't_ working but seems to be working now. I guess I'll reopen this if I can reproduce the issue. Thanks @schickling and @CompuIves !
