### ISSUE TITLE
Bug in calculation of "_raw.flattenedPath"

### ISSUE THREAD

**Issue by Oleksandr-Kei** [contentlayerdev/contentlayer#487]
There is a problem with `_raw.flattenedPath` in generated JSON schemas for content files.
If there is a file with "index" in the end of filename then this part will be erased in resulted value of `_raw.flattenedPath`
For example:
+ “search-by-index.mdx” will be resulted into “search-by-” in generated JSON schema;
+ “find-element-by-index.md” will be resulted into “find-element-by-“
+ “solution-documents/search-by-index.mdx” will be resulted into “solution-documents/search-by-“
+ “solution-documents/find-element-by-index.md” will be resulted into “solution-documents/find-element-by-”

![Screenshot (889)](https://github.com/contentlayerdev/contentlayer/assets/136618285/e057abca-b4b6-4b0e-8e95-e367ffd624f8)

Here is a repo to reproduce the issue: https://github.com/Oleksandr-Kei/contentlayer-project

Actual problem could be in this [line](https://github.com/contentlayerdev/contentlayer/blob/main/packages/%40contentlayer/source-files/src/fetchData/mapping/index.ts#L104)
Because `/\/?index$/` covers not only cases of "something/index" and "index". But also cases like "something-index", "somethingindex", etc.

**Comment by schickling** [comment]
This should be addressed with the [`0.3.4` release](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.3.4). 🎉
