### ISSUE TITLE
Invalid Markdown: failed with YAMLSemanticError: Insufficient indentation in flow collection when using TABS

### ISSUE THREAD

**Issue by cobbvanth** [contentlayerdev/contentlayer#488]
When using Tabs in JSON, inside of the front-matter of your mdx file, you will get the "failed with YAMLSemanticError: Insufficient indentation in flow collection" error when using tabs to indent multi-line separated arrays. 

![WindowsTerminal_HeEnB0ZRhO](https://github.com/contentlayerdev/contentlayer/assets/80018012/d6650458-0c61-46f6-b540-7e537df2a60b)

The following code with a single tab trigger this error: 
![Code_cYRcUyfVeZ](https://github.com/contentlayerdev/contentlayer/assets/80018012/f2ce8a78-a063-4fa7-a8d2-e8430b8c181a)

However, when this tab is replaced by spaces, the error no longer occurs:
![Code_j0h2eo5y8O](https://github.com/contentlayerdev/contentlayer/assets/80018012/1f6c86db-eb06-4e5c-8e59-71de7dfdc1d3)

The only other reference to this I came across was from the YAML repo here, which may indicate an issue with the version of YAML used in this repo. https://github.com/eemeli/yaml/issues/114

Thanks!

**Comment by schickling** [comment]
This should be addressed with the [`0.3.4` release](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.3.4). 🎉

**Comment by cobbvanth** [comment]
Awesome, thank you!
