### ISSUE TITLE
CLI is broken

### ISSUE THREAD

**Issue by zbeyens** [contentlayerdev/contentlayer#505]
After resetting my `yarn.lock`, running `yarn contentlayer <command>` outputs:

```tsx
file:///Users/zbeyens/GitHub/plate/node_modules/@effect-ts/otel/_mjs/Processor/Simple/index.mjs:7
import { ConsoleSpanExporter, SimpleSpanProcessor } from "@opentelemetry/sdk-trace-base";
         ^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'ConsoleSpanExporter' not found. The requested module '@opentelemetry/sdk-trace-base' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@opentelemetry/sdk-trace-base';
const { ConsoleSpanExporter, SimpleSpanProcessor } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async main (/Users/zbeyens/GitHub/plate/node_modules/contentlayer/bin/cli.cjs:4:19)
```

It still works if I don't reset my `yarn.lock`.

Using:
- node: v16.19.1
- yarn berry
- "next": "13.4.8",
- "next-contentlayer": "0.3.4",
- "contentlayer": "0.3.4",

**Comment by jahirfiquitiva** [comment]
I'm having the very same issue, and it breaks the build on Vercel 😭

**Comment by ThimoDEV** [comment]
Same issue here

**Comment by abdul-hamid-achik** [comment]
same here, i have the same next 13.4.9, content layer and next-contentlayer 0.3.4, node v20.0.0

**Comment by emkis** [comment]
I have the same problem, but it only happens when the Next config file uses ESM (`import/export`). I managed to make it work by temporarily changing the config file to `next.config.cjs`, and everything works well.

**Environment**
- `next`: 13.4.9
- `node`: 18.16.0
- `pnpm`: 8.6.2
- `contentlayer`: 0.3.4
- `next-contentlayer`: 0.3.4

**Comment by abdul-hamid-achik** [comment]
> I have the same problem, but it only happens when the Next config file uses ESM (`import/export`). I managed to make it work by temporarily changing the config file to `next.config.cjs`, and everything works well.
> 
> **Environment**
> 
> * `next`: 13.4.9
> * `node`: 18.16.0
> * `pnpm`: 8.6.2
> * `contentlayer`: 0.3.4
> * `next-contentlayer`: 0.3.4

oh wow, what a great tmpfix dude!

**Comment by XahidEx** [comment]
Also having the same issue

**Comment by XahidEx** [comment]
> I'm having the very same issue, and it breaks the build on Vercel sob

Changing region from function helped me. :) I know It sounds crazy

**Comment by wibb36** [comment]
This issue appears to be duplicated in [issue #506](https://github.com/contentlayerdev/contentlayer/issues/506), where a temporary solution has been provided; https://github.com/contentlayerdev/contentlayer/issues/506#issuecomment-1625210487

**Comment by stepcellwolf** [comment]
> > I have the same problem, but it only happens when the Next config file uses ESM (`import/export`). I managed to make it work by temporarily changing the config file to `next.config.cjs`, and everything works well.
> > **Environment**
> > 
> > * `next`: 13.4.9
> > * `node`: 18.16.0
> > * `pnpm`: 8.6.2
> > * `contentlayer`: 0.3.4
> > * `next-contentlayer`: 0.3.4
> 
> oh wow, what a great tmpfix dude!

For me, it does not work to build the GitHUb Action workflow. On the localhost, it is working. Any other suggestions?

`
Run npm run build

> pt-nextjs-blog @1.0.0 build
> cross-env INIT_CWD=$PWD next build

- info Loaded env from /home/runner/work/pt-nextjs-blog/pt-nextjs-blog/.env
- warn No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

- info Creating an optimized production build...
Failed to compile.

./app/about/page.tsx
Module not found: Package path ./generated is not exported from package /home/runner/work/pt-nextjs-blog/pt-nextjs-blog/node_modules/contentlayer (see exports field in /home/runner/work/pt-nextjs-blog/pt-nextjs-blog/node_modules/contentlayer/package.json)

https://nextjs.org/docs/messages/module-not-found

./app/blog/[...slug]/page.tsx
Module not found: Package path ./generated is not exported from package /home/runner/work/pt-nextjs-blog/pt-nextjs-blog/node_modules/contentlayer (see exports field in /home/runner/work/pt-nextjs-blog/pt-nextjs-blog/node_modules/contentlayer/package.json)

https://nextjs.org/docs/messages/module-not-found

./app/blog/page.tsx
Module not found: Package path ./generated is not exported from package /home/runner/work/pt-nextjs-blog/pt-nextjs-blog/node_modules/contentlayer (see exports field in /home/runner/work/pt-nextjs-blog/pt-nextjs-blog/node_modules/contentlayer/package.json)

https://nextjs.org/docs/messages/module-not-found

./app/blog/page/[page]/page.tsx
Module not found: Package path ./generated is not exported from package /home/runner/work/pt-nextjs-blog/pt-nextjs-blog/node_modules/contentlayer (see exports field in /home/runner/work/pt-nextjs-blog/pt-nextjs-blog/node_modules/contentlayer/package.json)

https://nextjs.org/docs/messages/module-not-found

./app/page.tsx
Module not found: Package path ./generated is not exported from package /home/runner/work/pt-nextjs-blog/pt-nextjs-blog/node_modules/contentlayer (see exports field in /home/runner/work/pt-nextjs-blog/pt-nextjs-blog/node_modules/contentlayer/package.json)

https://nextjs.org/docs/messages/module-not-found


> Build failed because of webpack errors
Error: Process completed with exit code 1.
`
