### ISSUE TITLE
Version 0.3.4 Broken on Vercel?

### ISSUE THREAD

**Issue by joergrech** [contentlayerdev/contentlayer#507]
As I'm using next-contentlayer this is a crosspost (https://github.com/shadcn/next-contentlayer/issues/11) but I hope some here had a similar problem and can give me a hint:
---
I get the following error on Vercel during the build of a production server - however it works on my local machine in dev and prod mode.

```
./pages/api/blog.rss.ts:1:30
12:47:21.431 | Type error: Cannot find module '@/.contentlayer/generated' or its corresponding type declarations.
12:47:21.431 |  
12:47:21.431 | > 1 \| import { allBlogposts } from "@/.contentlayer/generated"
12:47:21.431

<br class="Apple-interchange-newline">
```

I used the "@/.contentlayer/generated" from Vercel's example https://github.com/shadcn/next-contentlayer/blob/main/app/page.tsx but even with "contentlayer/generated" it works on my machine but not vercel. 

Btw. Visual Studio Code shows me a warn for "contentlayer/generated" (Cannot find module 'contentlayer/generated' or its corresponding type declarations.ts(2307)) - but as said running "yarn run dev" works fine.

I tried to add `contentlayer dev` before the build comman ("build": "contentlayer dev & next build") but that did not help either.

My package.json uses:
    "next-contentlayer": "^0.3.3",
    "contentlayer": "^0.3.3",
and yarn.lock uses contentlayer in version 0.3.4

Any ideas how I can fix or debug this?

**Comment by huanfe1** [comment]
Same problem.

I change `build` to `contentlayer build & next build`, It seem to resolve.

**Comment by yunsii** [comment]
> Same problem.
> 
> I change `build` to `contentlayer build & next build`, It seem to resolve.

Use `prebuild` script alternatively:

```json
{
  "prebuild": "contentlayer build",
  "build": "next build",
}
```
