### ISSUE TITLE
Request: Add CJS exports to the generated .contentlayer module

### ISSUE THREAD

**Issue by bearror** [contentlayerdev/contentlayer#51]
## Context

I've been trying out a combination of Next.js and Contentlayer, which works great. However, with Next 12 and the React Server Components alpha, there's a hurdle of Next being unable to build the server pages. It'll throw something like the following:
```
./pages/notes/[slug].server.tsx
Module not found: Package path ./data is not exported from package /x/node_modules/.contentlayer (see exports field in /x/node_modules/.contentlayer/package.json)
```

Looking at the `exports` field in the generated `package.json`, it is well-formed, e.g.
```json
{
  "exports": {
    "./data": {
      "import": "./data/index.mjs"
    },
    "./types": {
      "import": "./types/index.mjs"
    }
  }
}
```

That would suggest that, when building the pages, Next uses CommonJS, right? As a quick sanity-check, I tried copying over the generated `.contentlayer` module, renaming the `.mjs` files to plain `.js` files, and pointing the `exports` field to those, e.g.

```json
{
  "exports": {
    "./data": "./data/index.js",
    "./types": "./types/index.js"
  }
}
```

Then, I pointed the imports from `./pages/notes/[slug].server.tsx` to the copy, and the build passes once more.

## Request

It'd be awesome if the generated `.contentlayer` module would support importing via CommonJS as well as ES modules. While I'm sure there's a whole bunch of things to sort out with both React and Next before the server components eventually come out of alpha and beta, it seems to me that this would be enough to have a rough initial support. 😅

**Comment by schickling** [comment]
Sorry for the late response. Would be great if you could provide a reproduction repo for this issue. 🙏

**Comment by bearror** [comment]
Went to make a repro, and I suppose Next has changed to support ESM at build-time? 🤷‍♂️

No longer getting the issue when building on Node 16 — and the build error on Node 17 is due to React rather than Contentlayer. For context, it relates to the below deprecation message that is printed out when building on Node 16. After fixing that manually, Node 17 looks to build fine too with regards to Contentlayer.
> [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at ...

Anyway, here's a minimal example of using Next 12 and RSC just for giggles. https://github.com/bearror/contentlayer-next-12

---

I'll be closing the issue. The particular use-case here is with Next — and now that it handles the generated ESM client — there isn't a need to generate CJS. Perhaps there'll be some other use-case that comes up in the future, but that's for then 😄

**Comment by schickling** [comment]
Thanks for your help :)
