### ISSUE TITLE
Vercel build

### ISSUE THREAD

**Issue by DadaHumpa01** [contentlayerdev/contentlayer#527]
Hello everyone.
I am using this library for an application of mine in nextjs and I love it kudos to all.
I built a small cms, and through the api I create and edit static files I would like to ask you how can I during build in vercel edit or create my mdx files.
Thank you very much for your attention

**Comment by git-no** [comment]
@DadaHumpa01 
I would assume, you would get help much quicker if you would address your question in the [Discord Channel](https://discord.gg/rytFErsARm) of Contentlayer.

In general github issues are for repository / app issues, errors, feature requests, not for help, tutorials or learning questions.

Regards

**Comment by DadaHumpa01** [comment]
Ok, thank you very much, i wanted to ask if content layer is compatible with amazon bucket
