### ISSUE TITLE
Getting "Issues with peer dependencies found" on esbuild

### ISSUE THREAD

**Issue by tifandotme** [contentlayerdev/contentlayer#530]
```
 WARN  Issues with peer dependencies found
.
└─┬ contentlayer 0.3.4
  └─┬ @contentlayer/cli 0.3.4
    └─┬ @contentlayer/core 0.3.4
      └── ✕ unmet peer esbuild@"0.17.x || 0.18.x": found 0.19.1
```

I'm getting this warning after updating my packages. Will this be fixed? Or is there any way I can mitigate this, such as forcing pnpm to install ^0.18.0 version instead?

**Comment by Emperordmasac** [comment]
I'm also facing this issue, is there any solution or workaround

**Comment by kachkaev** [comment]
Looks like just extending version range might not work. `esbuild@0.19.0` contains breaking changes:
https://github.com/evanw/esbuild/releases/tag/v0.19.0

**Comment by kachkaev** [comment]
Not stale. Still seeing this warning in a project with up-to-date dependencies:

```txt
 WARN  Issues with peer dependencies found
apps/frontend
└─┬ contentlayer 0.3.4
  └─┬ @contentlayer/cli 0.3.4
    └─┬ @contentlayer/core 0.3.4
      └── ✕ unmet peer esbuild@"0.17.x || 0.18.x": found 0.19.5
```

**Comment by kachkaev** [comment]
not stale

**Comment by kachkaev** [comment]
not stale

**Comment by kachkaev** [comment]
not stale

**Comment by kachkaev** [comment]
🤔
