### ISSUE TITLE
[Warning] Contentlayer might not work as expected on Windows.

### ISSUE THREAD

**Issue by wooyng825** [contentlayerdev/contentlayer#532]
# [Trouble Issue]

╥
╠══╦══╗
║  ║  ║
║  ║  ╠─An interrupt was produced by #39.
║  ║  ║
║  ║  ▼
║  ║
║  ╠─An unchecked error was produced.
║  ║
║  ║ TypeError: Cannot read properties of undefined (reading 'tracer')
║  ║     at f (file:///C:/Workspace/blog/node_modules/@effect-ts/system/_src/Effect/derive.ts:88:76)
║  ║     at IRead.f (file:///C:/Workspace/blog/node_modules/@effect-ts/system/_src/Effect/has.ts:113:33)
║  ║     at FiberContext.evaluateNow (file:///C:/Workspace/blog/node_modules/@effect-ts/system/_src/Fiber/context.ts:1136:31)
║  ║     at file:///C:/Workspace/blog/node_modules/@effect-ts/system/_src/Fiber/context.ts:576:33
║  ║     at file:///C:/Workspace/blog/node_modules/@effect-ts/system/_src/Support/Scheduler/index.ts:15:9
║  ║
║  ║ Fiber: #41 (started at: 2023-08-19T07:12:24.885Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #41 (started at: 2023-08-19T07:12:24.885Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #41 (started at: 2023-08-19T07:12:24.885Z) was spawned by:
║  ║
║  ║ Fiber: #39 (started at: 2023-08-19T07:12:24.884Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #39 (started at: 2023-08-19T07:12:24.884Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #39 (started at: 2023-08-19T07:12:24.884Z) was spawned by:
║  ║
║  ║ Fiber: #37 (started at: 2023-08-19T07:12:24.882Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #37 (started at: 2023-08-19T07:12:24.882Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #37 (started at: 2023-08-19T07:12:24.882Z) was spawned by:
║  ║
║  ║ Fiber: #26 (started at: 2023-08-19T07:12:24.876Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #26 (started at: 2023-08-19T07:12:24.876Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #26 (started at: 2023-08-19T07:12:24.876Z) was spawned by:
║  ║
║  ║ Fiber: #5 (started at: 2023-08-19T07:12:24.454Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #5 (started at: 2023-08-19T07:12:24.454Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #5 (started at: 2023-08-19T07:12:24.454Z) was spawned by:
║  ║
║  ║ Fiber: #0 (started at: 2023-08-19T07:12:24.434Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #0 (started at: 2023-08-19T07:12:24.434Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #0 (started at: 2023-08-19T07:12:24.434Z) was spawned by: <empty trace>
║  ▼
▼

OS: win32 10.0.22621 (arch: x64)
Process: C:\Program Files\nodejs\node.exe C:\Workspace\blog\node_modules\next\dist\compiled\jest-worker\processChild.js
Node version: v18.15.0
Contentlayer version: 0.3.4

<br />
<br />
<br />

# [Temporary Solution that I found]
### **contentlayer & next-contentlayer** package version : ***0.3.3▲  → 0.3.2*** (identical version)

**Comment by wooyng825** [comment]
## [Temporary Solution that I found]
#### **next-contentlayer** package version : ***0.3.3▲  → 0.3.2***

**Comment by trevorpfiz** [comment]
I am having this issue with WSL2

Node version: v18.17.1
Contentlayer version: 0.3.4

**Comment by trevorpfiz** [comment]
my fields were just not set correctly.

```
title: title
description: description
image: /assets/posts/short-guide-to-component-naming/typewriter.jpg
datePublished: 2022-12-01
dateModified: 2022-12-01
author:
name: Trevor,
role: Founder,
```
  
to
  
```
title: title
description: description
image: /assets/posts/short-guide-to-component-naming/typewriter.jpg
datePublished: 2022-12-01
dateModified: 2022-12-01
author:
  {
    name: Trevor Pfizenmaier,
    role: Founder,
  }
```
