### ISSUE TITLE
Importing `next-contentlayer/hooks` breaks pages using `getServerSideProps` in Vercel

### ISSUE THREAD

**Issue by EthanStandel** [contentlayerdev/contentlayer#54]
![image](https://user-images.githubusercontent.com/16840301/142800244-bf6b9443-9429-49f3-b673-e385f58aee56.png)

**Comment by schickling** [comment]
Which version of Next.js are you using? Contentlayer requires ESM so this probably just works in Next.js 12+.

**Comment by EthanStandel** [comment]
I am using Next@12 and it runs fine on the local builds. It's only an issue when deployed to Vercel (which I assume is where a good amount of Next apps are deployed).

Also might be worth noting the project was initialized to Next@11 but the [upgrade guide](https://nextjs.org/docs/upgrading) is fairly simple and doesn't include anything that mentions ESM vs CommonJS.

**Comment by schickling** [comment]
@EthanStandel thanks for clarifying.

I've just released a new `dev` version which hopefully addresses the problem you're facing. Could you please give it a try via `yarn add contentlayer@dev next-contentlayer@dev`? (Should install `0.0.34-dev.2`)

**Comment by EthanStandel** [comment]
@schickling hey that did it! I'll close this out. 

Unrelated, but likely useful information for the future that I forgot to note: if anything weird with Vercel itself comes up again, it's worth noting that they're stuck on Node@14.x for their serverless functions.
