### ISSUE TITLE
Cannot import "*.module.css" into a JavaScript file without an output path configured

### ISSUE THREAD

**Issue by JamesIves** [contentlayerdev/contentlayer#542]
### Issue

I am parsing my blog with `next-contentlayer` with the `useMDXComponent` hook. Whenever it encounters an mdx file that imports a component with a CSS Module import, I get an error:

```
✘ [ERROR] Cannot import "../app/components/blog/CatAnimationExample/CatAnimationExample.module.css" into a JavaScript file without an output path configured

Error: Found 1 problems in 27 documents.

 └── Encountered unexpected errors while processing of 1 documents. This is possibly a bug in Contentlayer. Please open an issue.
     
     • "2020-12-12-animating-sprite-sheets-with-css.mdx": UnexpectedMDXError: Error: Build failed with 1 error:
     ../app/components/blog/CatAnimationExample.tsx:2:24: ERROR: Cannot import "../app/components/blog/CatAnimationExample/CatAnimationExample.module.css" into a JavaScript file without an output path configured
```

The React component looks like the following, it is imported at the top of my .mdx file.

```jsx
import * as styles from './CatAnimationExample/CatAnimationExample.module.css'

export default function CatAnimationExample({example}: CatAnimationExampleProps) {
   return (
      <div className={styles.example}>content</div>
    )
}
```

I am able to generally import this file into a `page.tsx` component without issue, it's only if that component gets parsed by contentlayer does the error surface. My ultimate goal here is to code split blog-specific components so I'm not unnecessarily loading them within my global style sheet. 

Is there some additional configuration needed here? 

### Environment
* contentlayer **0.3.4**
* next-contentlayer **0.3.4**
* next **13.4.13**

**Comment by notfathomless** [comment]
Same issue here, any update on this?
