### ISSUE TITLE
RemarkPlugins and rehypePlugins are not effective

### ISSUE THREAD

**Issue by imyuanli** [contentlayerdev/contentlayer#545]
`
export default makeSource({
    contentDirPath: 'posts',
    documentTypes: [Post],
    mdx: {
        remarkPlugins: [
            remarkExtractFrontmatter,
            remarkGfm,
            remarkMath,
            remarkImgToJsx,
        ],
        rehypePlugins: [
            rehypeSlug,
            rehypeAutolinkHeadings,
            rehypeKatex, ,
        ],
    },
})

`
This is my configuration item, but it seems that none of them have taken effect. I only need to delete the cache file and run it again to take effect. However, every time I delete the cache file, I need to download the node_module again for the project to run well.

**Comment by tifandotme** [comment]
I think you need to wrap each plugins in brackets as an array, like so:

```ts
export default makeSource({
  contentDirPath: "posts",
  documentTypes: [Post],
  mdx: {
    remarkPlugins: [
      [remarkExtractFrontmatter],
      [remarkGfm],
      [remarkMath],
      [remarkImgToJsx],
    ],
    rehypePlugins: [[rehypeSlug], [rehypeAutolinkHeadings], [rehypeKatex], ,],
  },
})
```
