### ISSUE TITLE
ContentLayer and rehype-highlight v7.0

### ISSUE THREAD

**Issue by dstroot** [contentlayerdev/contentlayer#549]
FYI: New version of rehype-highlight just released (v7.0). Does not work with content layer. Has a strange typescript error. Reverted to 6.0 and all is good. 

Node 18.17.1
Nextjs 13.4.19
ContentLayer 0.3.4

**Comment by paulcjy** [comment]
Using `() => highlight` instead of `highlight` works for rehype-highlight v7.0.0
