### ISSUE TITLE
Error with content layer notion

### ISSUE THREAD

**Issue by kmclaugh** [contentlayerdev/contentlayer#551]
I have nextjs with an app router in a monorepo. I get this error when trying to use the contentlayer notion integration

This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
https://github.com/contentlayerdev/contentlayer/issues

╥
╠══╦══╗
║  ║  ║
║  ║  ╠─An interrupt was produced by #6.
║  ║  ║
║  ║  ▼
║  ║
║  ╠─An unchecked error was produced.
║  ║
║  ║ TypeError: Cannot read properties of undefined (reading 'tracer')
║  ║     at f (file:///Users/kevinmclaughlin/projects/sliderule-analytics/sliderule/node_modules/@effect-ts/system/_src/Effect/derive.ts:88:76)
║  ║     at IRead.f (file:///Users/kevinmclaughlin/projects/sliderule-analytics/sliderule/node_modules/@effect-ts/system/_src/Effect/has.ts:113:33)
║  ║     at FiberContext.evaluateNow (file:///Users/kevinmclaughlin/projects/sliderule-analytics/sliderule/node_modules/@effect-ts/system/_src/Fiber/context.ts:1136:31)
║  ║     at file:///Users/kevinmclaughlin/projects/sliderule-analytics/sliderule/node_modules/@effect-ts/system/_src/Fiber/context.ts:576:33
║  ║     at file:///Users/kevinmclaughlin/projects/sliderule-analytics/sliderule/node_modules/@effect-ts/system/_src/Support/Scheduler/index.ts:15:9
║  ║     at processTicksAndRejections (node:internal/process/task_queues:95:5)
║  ║
║  ║ Fiber: #20 (started at: 2023-09-08T15:21:53.228Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #20 (started at: 2023-09-08T15:21:53.228Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #20 (started at: 2023-09-08T15:21:53.228Z) was spawned by:
║  ║
║  ║ Fiber: #6 (started at: 2023-09-08T15:21:52.336Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #6 (started at: 2023-09-08T15:21:52.336Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #6 (started at: 2023-09-08T15:21:52.336Z) was spawned by: <empty trace>
║  ▼
▼

OS: darwin 21.3.0 (arch: x64)
Process: /Users/kevinmclaughlin/Library/pnpm/nodejs/18.17.1/bin/node /Users/kevinmclaughlin/projects/sliderule-analytics/sliderule/node_modules/.bin/contentlayer build
Node version: v18.17.1
Contentlayer version: 0.3.4

**Comment by olivierreuland** [comment]
I'm seering a similar issue:
`Contentlayer config change detected. Updating type definitions and data...
This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
https://github.com/contentlayerdev/contentlayer/issues

╥
╠══╦══╗
║  ║  ║
║  ║  ╠─An interrupt was produced by #39.
║  ║  ║ 
║  ║  ▼
║  ║
║  ╠─An unchecked error was produced.
║  ║ 
║  ║ TypeError: Cannot read properties of undefined (reading 'tracer')
║  ║     at f (file:///Users/olivier/Dev/whcnz/node_modules/@effect-ts/system/_src/Effect/derive.ts:88:76)
║  ║     at IRead.f (file:///Users/olivier/Dev/whcnz/node_modules/@effect-ts/system/_src/Effect/has.ts:113:33)
║  ║     at FiberContext.evaluateNow (file:///Users/olivier/Dev/whcnz/node_modules/@effect-ts/system/_src/Fiber/context.ts:1136:31)
║  ║     at file:///Users/olivier/Dev/whcnz/node_modules/@effect-ts/system/_src/Fiber/context.ts:576:33
║  ║     at file:///Users/olivier/Dev/whcnz/node_modules/@effect-ts/system/_src/Support/Scheduler/index.ts:15:9
║  ║ 
║  ║ Fiber: #41 (started at: 2023-09-22T05:24:02.757Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #41 (started at: 2023-09-22T05:24:02.757Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #41 (started at: 2023-09-22T05:24:02.757Z) was spawned by:
║  ║ 
║  ║ Fiber: #39 (started at: 2023-09-22T05:24:02.757Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #39 (started at: 2023-09-22T05:24:02.757Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #39 (started at: 2023-09-22T05:24:02.757Z) was spawned by:
║  ║ 
║  ║ Fiber: #37 (started at: 2023-09-22T05:24:02.757Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #37 (started at: 2023-09-22T05:24:02.757Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #37 (started at: 2023-09-22T05:24:02.757Z) was spawned by:
║  ║ 
║  ║ Fiber: #26 (started at: 2023-09-22T05:24:02.754Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #26 (started at: 2023-09-22T05:24:02.754Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #26 (started at: 2023-09-22T05:24:02.754Z) was spawned by:
║  ║ 
║  ║ Fiber: #5 (started at: 2023-09-22T05:24:02.620Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #5 (started at: 2023-09-22T05:24:02.620Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #5 (started at: 2023-09-22T05:24:02.620Z) was spawned by:
║  ║ 
║  ║ Fiber: #0 (started at: 2023-09-22T05:24:02.614Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #0 (started at: 2023-09-22T05:24:02.614Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #0 (started at: 2023-09-22T05:24:02.614Z) was spawned by: <empty trace>
║  ▼
▼

OS: darwin 22.6.0 (arch: arm64)
Process: /Users/olivier/.nvm/versions/node/v20.5.1/bin/node /Users/olivier/Dev/whcnz/node_modules/next/dist/server/lib/start-server.js
Node version: v20.5.1
Contentlayer version: 0.3.4`

**Comment by muharu** [comment]
i have same problem
