### ISSUE TITLE
Issue with foreign characters

### ISSUE THREAD

**Issue by hoonblizz** [contentlayerdev/contentlayer#554]
Hi, 

Not sure where this issue is coming from but I'm trying to implement 2 things:
- Next 13
- Contentlayer

In local environment, there's no issue at all. 
When it comes to prod, (I'm using AWS S3 for static hosting)
it gets me the following error.

```
SyntaxError: Unexpected token '한', ..."00\\uB2A5\한 \\uB180\"... is not valid JSON
    at JSON.parse (<anonymous>)
    at 12694 (781-7ce873b7c2a3a830.js:1:353)
    at s (webpack-92af148b2d97d254.js:1:151)
    at 65857 (page-623c86b8da64ad0d.js:1:206)
    at s (webpack-92af148b2d97d254.js:1:151)
    at S (596-100846a90423a0a4.js:9:2045)
    at P (596-100846a90423a0a4.js:9:1313)
    at 596-100846a90423a0a4.js:9:6084
```

The application supports 3 languages, English, Spanish and Korean.
The character `한` is from Korean contents (mdx file)
When I deleted the whole Korean contents and published, the issues are gone and application works fine. 

Currently using:
```
"contentlayer": "^0.3.1",
"next-contentlayer": "^0.3.1",
"next": "^13.4.0",
```

But the latest version was the same.
Also, I use `output: 'export'` for static hosting in S3.

Currently I deleted all `date` related stuff and modified all components into the following format
```
const Whatever = () => {}
default export Whatever;
``` 
just to avoid `use client` error that could possibly happen.

Any idea what's causing this? 
Thank you!

**Comment by hoonblizz** [comment]
Found the issue.
When I `contentlayer dev`, then access to the troubling content in `.contentlayer` folder, 
It looks like, 

```
children:[\"Pedometer \\uB294 \\uC13C\\uC11C\\uB85C step\\uC744 \\uCE21\\uC815 \\uAC00\\uB2A5\\uD55C \\uB180\\uB77C\\uC6B4 package \\uC774\\uB2E4.\",
```

Then when I build, in `out` folder, the same content looks like, 

```
children:[\\"Pedometer \\\\uB294 \\\\uC13C\\\\uC11C\\\\uB85C step\\\\uC744 \\\\uCE21\\\\uC815 \\\\uAC00\\\\uB2A5\\\uD55C \\\\uB180\\\\uB77C\\\\uC6B4 package \\\\uC774\\\\uB2E4.\\",
```

There's a lot more back slash involved here.

**Comment by HiimKwak** [comment]
Same issues here. Can't build content with Korean characters😿

**Comment by InhwanCho** [comment]
same issue

**Comment by Seokho0120** [comment]
same..........................korean characters....

**Comment by Seokho0120** [comment]
hi. I too have been struggling with the same problem for several days.

I ended up downgrading the versions of nextjs and contentlayer.

In the end, I solved these problems, and both build and deployment worked normally.

my nextjs version is '13.5.4' and contentlayer version is '0.3.4'.

I hope these problems are resolved as soon as possible.

Thank you🥲

**Comment by harryhan24** [comment]
I couldn't solve this problem either

**Comment by hoonblizz** [comment]
Small update here.
Couldn't deal with the issue but just giving up `mdx` format could resolve my issue (at least).
Feels not right giving up such useful tool but....better than not working (or waiting for fix).

So, in summary:
- Give up `mdx` and use `md`
- If using vscode, try markdown lint extension to avoid mistakes in format
- My current setup in `next.config.js` (Again, I run static contents)
```js
const { withContentlayer } = require("next-contentlayer");

const nextConfig = {
  output: 'export',
  reactStrictMode: true, 
  swcMinify: true,
  compress: true,
  images: {
    unoptimized: true
  },
};

module.exports = withContentlayer(nextConfig);
```

Well, it's unfortunate to say that I couldn't find a proper solution. 
Hopefully someone else finds it. 😄
