### ISSUE TITLE
How exactly do you add boolean to a mdx file ?

### ISSUE THREAD

**Issue by Joshuajrodrigues** [contentlayerdev/contentlayer#559]
my contentLayer config looks like this
```
featured: {
      type: "boolean",
      default: false,
      required: false,
    },
    component: {
      type: "boolean",
      default: false,
      required: false,
    },
    toc: {
      type: "boolean",
      default: true,
      required: false,
    },
```

and my mdx file looks kinda like this

```
---
title: Hello
description: World
featured: true
component: true
toc: true
---

stuff stuff

```

but this gives me an error saying component is invalid, Ive changed the type to string and then it works, so Im guessing its because it parses component: true as a string

**Comment by laanayam333** [comment]
Any news on this issue? I'm having the same problem.

This is how I'm defining the boolean in my schema: 


This is my frontmatter:

---
title: 2023 reading list
publishedAt: "2023-10-26"
summary: xxx
isFeatured: false
---

**Comment by Joshuajrodrigues** [comment]
> Any news on this issue? I'm having the same problem.
> 
> This is how I'm defining the boolean in my schema: 
> 
> 
> This is my frontmatter:
> 
> ---
> title: 2023 reading list
> publishedAt: "2023-10-26"
> summary: xxx
> isFeatured: false
> ---

I just ended up using it as string as it seems to give the least issues with that approach in my case. Maybe i shouldn't have closed this.

**Comment by Joshuajrodrigues** [comment]
> > Any news on this issue? I'm having the same problem.
> > 
> > This is how I'm defining the boolean in my schema: 
> > 
> > 
> > This is my frontmatter:
> > 
> > ---
> > title: 2023 reading list
> > publishedAt: "2023-10-26"
> > summary: xxx
> > isFeatured: false
> > ---
> 
> I just ended up using it as string as it seems to give the least issues with that approach in my case. Maybe i shouldn't have closed this as you also have the same issue.

**Comment by laanayam333** [comment]
I kind of got it working with the boolean type by moving the property to the top of the frontmatter.

**Boolean Type in Schema**

```js
  isFeatured: {
      type: "boolean",
      default: false,
    }
```

**Frontmatter in .mdx file**

```mdx
  ---
  isFeatured: true
  title: 2023 reading list
  publishedAt: 2023-10-26
  summary: xxx
  ---
```

I'm not sure why the error is gone by doing this, but as far as I can see, when the boolean property was under another property of type string, it would be parsed as a string for some reason.
