### ISSUE TITLE
feat: configurable working directory

### ISSUE THREAD

**Issue by samyosm** [contentlayerdev/contentlayer#563]
We aren't able to configure the `.contentlayer` output location.

## Uses

- Cleanly support multiple sites/apps
- Ability to be used with monorepos

## Context

Appropriate lines of code:
https://github.com/samyosm/contentlayer/blob/2f491c540e1d3667577f57fa368b150bff427aaf/packages/%40contentlayer/core/src/_ArtifactsDir.ts#L12-L13

## Related

#464

**Comment by harrysolovay** [comment]
Current examples show generated assets imported via `contentlayer/generated`, which is aliased via `paths` in the `tsconfig.json`. Many folks will already alias their root directory (for instance, shadcn ui projects are generated with the alias `@/[subdir]`). One could forgo the second alias and instead import from `@/.contentlayer`, however it's a bit clunky. Ideally one could configure the output directory to enable a more minimal import specifier (`@/content` perhaps). Any chance we could reopen this issue?
