### ISSUE TITLE
Numbered Lists nit rendering correctly

### ISSUE THREAD

**Issue by farid98** [contentlayerdev/contentlayer#565]
Numbered lists in Markdown not rendering correctly. e.g. if I have this markdown in the Post:

1. One
2. Two
3. Three

The output does not have the numbers and looks like this

One
Two
Three

**Comment by johnpaulkiser** [comment]
If you inspect the rendered element on the page you should find that it is properly rendered into:

```html
<ol>
  <li>One</li>
  <li>Two</li>
  <li>Three</li>
</ol>
```

My guess is that you are using the default example using tailwind which resets `list-style` to `none` on list item elements.

More here:
https://github.com/tailwindlabs/tailwindcss.com/issues/850

This should likely be mentioned in the contentlayer docs or the default example shouldn't use tailwind.

**Comment by farid98** [comment]
Thanks. Yes I used the example as the starting point and this is the issue. 

Thanks for the help and clarification.

**Comment by johnpaulkiser** [comment]
Yup!

I recommend using [@tailwind/typography-plugin](https://tailwindcss.com/docs/typography-plugin) to solve this.

**Comment by farid98** [comment]
Yes, the plugin worked perfectly. After adding the plugin the following generates the list with numbers 

<article className="prose prose-ui:list-disc">
      <Content /> 
</article>

**Comment by farid98** [comment]
Plugin woks perfectly. Thanks.

After installing the plugin, the following generates the list correctly

```
<article className="prose prose-ui:list-disc">
      <Content /> 
</article>

```
