### ISSUE TITLE
navigate up (..) does not work in filePathPattern

### ISSUE THREAD

**Issue by hardyyb2** [contentlayerdev/contentlayer#572]
Hello everyone

I am using contentlayer with next 13 for creating blogs. 
Although using `filePathPattern: "../**/*.info.mdx"` does not work. 

* I have all the content I want to generate in `app/_content` folder so the `contentDirPath` is the same. 
* But I want a `*.info.mdx` file at any level in our out of `app/_content` folder. 
* I do not want to change the `contentDirPath` since I want to keep all other data there.

A similar replication can be found here - https://stackblitz.com/edit/stackblitz-starters-rrscwz?file=contentlayer.config.ts

Is this a bug or is it supposed to work this way?

Thank you

**Comment by NoneWofie** [comment]
@hardyyb2 Have you solved it?
