### ISSUE TITLE
failed with YAMLParseError

### ISSUE THREAD

**Issue by XahidEx** [contentlayerdev/contentlayer#584]
Unexpected scalar at node end at line 4, column 201: (like this). 
This error occurs when I'm adding a new mdx. Even if It's as simple as this:

```
---
title: 'test'
publishedAt: '2023-12-12'
summary: 'test'
---

Test
```
This is a problem with the latest contentlayer. (I'm using next14)

**Comment by PxlSyl** [comment]
Hello, same problem here

**Comment by chupAkabRRa** [comment]
If you experience this issue on Windows, try to replace line endings in your .mdx files from CRLF to just LF. Should fix the issue

**Comment by mischiefCloud** [comment]
> If you experience this issue on Windows, try to replace line endings in your .mdx files from CRLF to just LF. Should fix the issue

This works to fix the issue.

**Comment by gautamankoji** [comment]
> summary: 'test'

Remove the quotes from `summary`

**Change this:**  
```yaml
summary: 'test'
```

**To this:**  
```yaml
summary: test
```  

unnecessary quotes can cause YAML parsing issues
