### ISSUE TITLE
ERROR: when trying to install next-contentlayer in Next.js @14

### ISSUE THREAD

**Issue by tnnz20** [contentlayerdev/contentlayer#588]
I'm trying to install next-contentlayer in Next.js 14 but got this error

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: gozy@0.1.0
npm ERR! Found: next@14.0.1
npm ERR! node_modules/next
npm ERR!   next@"14.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^12 || ^13" from next-contentlayer@0.3.4
npm ERR! node_modules/next-contentlayer
npm ERR!   next-contentlayer@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\USER\AppData\Local\npm-cache\_logs\2023-11-07T16_25_24_233Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\USER\AppData\Local\npm-cache\_logs\2023-11-07T16_25_24_233Z-debug-0.log
```

another option is adding --force or --legacy-peer-deps but if im trying to install another package this error will appear again

Node version = 18.17.0
Next version = 14.0.1

**Comment by shaikahmadnawaz** [comment]
I am also facing the same error.

**Comment by laanayam333** [comment]
There's a pull request from a couple of weeks ago that fixes the legacy peer deps issue for Next 14. It's still waiting to be merged.

**Comment by hyn-lei** [comment]
mark, notify when the pull request be merged...

**Comment by sanne-v** [comment]
Please merge this https://github.com/contentlayerdev/contentlayer/pull/576/files

**Comment by orafaelfragoso** [comment]
Quick workaround, just add that to package.json
```json
  "overrides": {
    "next-contentlayer": {
      "next": "$next"
    }
  }
  ```

**Comment by hyn-lei** [comment]
> Quick workaround, just add that to package.json
> 
> ```json
>   "overrides": {
>     "next-contentlayer": {
>       "next": "$next"
>     }
>   }
> ```

thanks, this is a nice solution..

**Comment by peduarte** [comment]
Saaaaame 😄

**Comment by kaikun213** [comment]
Still no support, any news on updates?
