### ISSUE TITLE
Question: How to structure content?

### ISSUE THREAD

**Issue by cjroebuck** [contentlayerdev/contentlayer#59]
Hey schickling, looking to use contentlayer on my docs site at urlbox.io after seeing it in leerob's repo, looks great.

Quick question I have before getting too stuck in, how would I be able to structure the content, I'm currently using a manifest.json like next.js docs (https://github.com/vercel/next.js/blob/master/docs/manifest.json) and formik-docs (https://github.com/formium/formik/blob/master/docs/manifest.json) in order to structure the individual mdx posts, so that they can be structured correctly in the sidebar.

This also allows adding next and previous links at the bottom of each article to navigate to sibling docs. Just wondering if this is possible currently with contentlayer or how to go about it?

A lot of the examples seem to just order a list of content by date, whereas for docs sites, we'd need more structure / a pre-defined order.

**Comment by schickling** [comment]
Hey @cjroebuck thanks a lot for raising this great question. I've been thinking about the same a few times but haven't reached a comprehensive conclusion. Would love to discuss this further with you (and others) in Discord: https://discord.gg/fk83HNECYJ

**Comment by schickling** [comment]
@cjroebuck my current thinking and explorations are going in a similar direction to how the [Prisma docs are structured](https://github.com/prisma/docs/tree/main/content). This way of structuring the content provides a straightforward way to organize the content in a hierarchy (similar to how Next.js routes work) and also allows you to define a "sort order" via the number-based prefixing.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/1567498/144493347-8922738b-8b65-4eee-89a5-fc0bf242db24.png">

I'm also currently giving this approach a try for the WIP Contentlayer docs/website (https://github.com/contentlayerdev/website/pull/2)

**Comment by cjroebuck** [comment]
@schickling Cool, this method was something I'd thought of too, I like the simplicity and the similarity to next.js' philosophy of page and api routes. 

The only issue I had with it is when you want to insert a doc in-between two already ordered docs, like between 001 and 002-..., would you now need to rename all other files 002->003, 003->004 and so on? 

I guess you have more experience with this if it's how prisma's docs are working, so perhaps it's not worth worrying about. How often do insertions happen that cause renumberings in prisma's docs?

**Comment by schickling** [comment]
That's indeed a downside of this approach which however can be mitigated quite easily if e.g. you "leave space" between existing documents (e.g. see picture above). Also seems like someone has created [a little CLI tool](https://github.com/prisma/docs#inserting-moving-and-deleting-files) for exactly that workflow 🙃

**Comment by cjroebuck** [comment]
Sounds good to me, I think this is really the simplest way without reverting to manifest files.
