### ISSUE TITLE
Warning: Contentlayer might not work as expected on Windows

### ISSUE THREAD

**Issue by MarioGRodriguez28** [contentlayerdev/contentlayer#593]
> 02-next-blog-mdx@0.1.0 dev
> contentlayer build && next dev

Warning: Contentlayer might not work as expected on Windows
NoConfigFoundError {
  cwd: 'C:/Users/MarioG/OneDrive/Documents/Coding/ReactJs-NextJs/curso-de-next/02-next-blog-mdx',
  configPath: undefined,
  _tag: 'NoConfigFoundError',
  toString: [Function (anonymous)],
  [Symbol()]: {
    cwd: 'C:/Users/MarioG/OneDrive/Documents/Coding/ReactJs-NextJs/curso-de-next/02-next-blog-mdx',
    configPath: undefined
  },
  [Symbol()]: [ 'configPath', 'cwd' ]

**next.config.js**
`const { withContentlayer } = require("next-contentlayer");

/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
};

module.exports = withContentlayer(nextConfig);

`
**tsconfig.json**
`{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"],
      "contentlayer/generated": ["./.contentlayer/generated"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", ".contentlayer/generated"],
  "exclude": ["node_modules"]
}
`

**contentlayer.config.tsx**

`// contentlayer.config.js

import { defineDocumentType, makeSource } from "contentlayer/source-files";

export const Post = defineDocumentType(() => ({
  name: "Post",
  filePathPattern: `**/*.mdx`,
  contentType: "mdx",
  fields: {
    title: {
      type: "string",
      description: "The title of the post",
      required: true,
    },
    description: {
      type: "string",
      description: "The description of the post",
      required: true,
    },
    date: {
      type: "date",
      description: "The date of the post",
      required: true,
    },
  },
  computedFields: {
    url: {
      type: "string",
      resolve: (post) => `/posts/${post._raw.flattenedPath}`,
    },
  },
}));

export default makeSource({
  contentDirPath: "posts",
  documentTypes: [Post],
});
`
**package.json**

`{
  "name": "02-next-blog-mdx",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "contentlayer build && next dev",
    "build": "contentlayer build && next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "contentlayer": "^0.3.1",
    "date-fns": "^2.30.0",
    "next": "13.5.6",
    "next-contentlayer": "^0.3.1",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10",
    "postcss": "^8",
    "tailwindcss": "^3",
    "typescript": "^5"
  }
}
`

**Comment by drewdoesdev** [comment]
Hello @MarioGRodriguez28.  I see that this issue is marked as completed, however i'm still seeing it on Windows 10 (node 21).  Do you know what the solution was here?
