### ISSUE TITLE
Is it possible to access the "text" mdx body for a `computedFields`? (Attempting to make a read time estimate)

### ISSUE THREAD

**Issue by Blankeos** [contentlayerdev/contentlayer#595]
What I'm trying to add is this [`reading-time`](https://www.npmjs.com/package/reading-time) estimator function to calculate "4 mins read" or whatever similar to Medium's article posts.

Is there any way I can access the `body.code` at build time? I want to at least try getting the raw text, then give a 'read time' estimate somewhere.

![image](https://github.com/contentlayerdev/contentlayer/assets/38070918/b7330da4-7821-45ef-9a60-dffcde828714)

---

EDIT: just found a possible workaround, which is to use node fs to readFileSync and get the markdown body myself.

**Comment by Blankeos** [comment]
Here's what worked:
```ts
import fs from 'node:fs'
import readingTime from 'reading-time'

... // <- collapsed in between.

  computedFields: {
    readTimeStats: {
      type: 'nested',
      resolve: (post) => {
        const content = fs.readFileSync(
          path.join('content', post._raw.sourceFilePath), // I have a content/posts/*.mdx filePath pattern, this is why I have 'content'
          'utf-8'
        )

        const body = content.split('---').at(-1)?.trim() ?? ''

        return readingTime(body)
      },
    },
... // <- collapsed everything else
```

This way, I'm able to get variables like these:

![image](https://github.com/contentlayerdev/contentlayer/assets/38070918/1f188537-25b5-4639-87e6-9bec55f2b8b3)

🥳🙌 Anyway, that's all. Feel free to close this if you think this is already a good workaround. Keep it open if you want to support it as an actual feature later on.

**Comment by devopsbarista** [comment]
@Blankeos Unless I'm missing something, the above can be achieved with no workarounds:

```js
import readingTime from 'reading-time'

computedFields: {
    readTimeStats: { type: 'json', resolve: (doc) => readingTime(doc.body.raw) },
}
```
