### ISSUE TITLE
TypeError: The "code" argument must be of type number. Received an instance of Object

### ISSUE THREAD

**Issue by gmcamposano** [contentlayerdev/contentlayer#598]
I am getting this error with `npx contentlayer build`
```
Generated 2 documents in .contentlayer
TypeError: The "code" argument must be of type number. Received an instance of Object
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at Cli.runExit (/home/gabriel/Desktop/markdown-app/node_modules/clipanion/lib/advanced/Cli.js:232:26)
    at run (file:///home/gabriel/Desktop/markdown-app/node_modules/@contentlayer/cli/src/index.ts:39:3)
    at main (/home/gabriel/Desktop/markdown-app/node_modules/contentlayer/bin/cli.cjs:5:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
Anyone else?

**Comment by jrolfs** [comment]
Yeah, see https://github.com/contentlayerdev/contentlayer/issues/495. It's related to [Cli#runExit](https://mael.dev/clipanion/docs/api/cli#clirunexit) and this:

> This is related to Node Deprecation [DEP0164 (process.exit(code), process.exitCode coercion to integer](https://nodejs.org/api/deprecations.html#DEP0164).

It seems the build command is yielding an object instead of an exit code `number`. I'm going to open a PR for this and I'll also add a workaround to the comments in #495.

**Comment by gmcamposano** [comment]
> Yeah, see #495. It's related to [Cli#runExit](https://mael.dev/clipanion/docs/api/cli#clirunexit) and this:
> 
> > This is related to Node Deprecation [DEP0164 (process.exit(code), process.exitCode coercion to integer](https://nodejs.org/api/deprecations.html#DEP0164).
> 
> It seems the build command is yielding an object instead of an exit code `number`. I'm going to open a PR for this and I'll also add a workaround to the comments in #495.

Thank you for your quick reply. So its basically related to Node. Meanwhile, i am able to build normally on Node 20.9.0 but with the error shown above.

**Comment by dogcity** [comment]
Hi, I also have the same error, but the compilation goes fine.

**Comment by Taimoorkhan1122** [comment]
Hi, having same issue

```The "code" argument must be of type number. Received an instance of Object```

**Comment by FelipeFTN** [comment]
I Just executed using **Sudo** (Administrator permissions) and it just worked! :rocket:

**Comment by kachkaev** [comment]
oh no, not stale 😞

**Comment by vincent-thomas** [comment]
i have this issue too

**Comment by igormcsouza** [comment]
> Yeah, see #495. It's related to [Cli#runExit](https://mael.dev/clipanion/docs/api/cli#clirunexit) and this:
> 
> > This is related to Node Deprecation [DEP0164 (process.exit(code), process.exitCode coercion to integer](https://nodejs.org/api/deprecations.html#DEP0164).
> 
> It seems the build command is yielding an object instead of an exit code `number`. I'm going to open a PR for this and I'll also add a workaround to the comments in #495.

Downgrade to node v18.20 worked for me! Issue is gone.. I'll be still tracking that to get the fix for Node v20!

**Comment by xingBaGan** [comment]
Downgrade to node v18.20.4 worked for me! Issue is gone.. I'll be still tracking that to get the fix for Node v21!  		
version: "contentlayer": "^0.3.4",

**Comment by edward-meister** [comment]
same issue
