### ISSUE TITLE
Make effect peerDependency

### ISSUE THREAD

**Issue by mikearnaldi** [contentlayerdev/contentlayer#6]
Effect is currently loaded via `utils` as a dependency while it should be loaded as peerDependency. Linking libs as deps is generally unadvisable for any dependency but poses a critical risk for effect (and its ecosystem packages) in particular given that it doesn't work if multiple copies are loaded.

https://github.com/contentlayerdev/contentlayer/blob/main/packages/%40contentlayer/utils/package.json#L43

Note that multiple copies will be loaded any time a user of the lib installs a different version of effect (even a patch) in a child project, that isn't the case for peerDependencies with a set range of acceptable versions

**Comment by schickling** [comment]
Addressed by #7193a37
