### ISSUE TITLE
Compatibility issues.

### ISSUE THREAD

**Issue by Gerald-ux-ux** [contentlayerdev/contentlayer#606]
Content layer is not supported by Next 14.0.1

`npm ERR! While resolving: next-contentlayer@0.3.4
npm ERR! Found: next@14.0.1`

Thats the error i keep getting. How can i resolve the issue?

**Comment by jkeussen** [comment]
I have the same issue.

**Comment by jkeussen** [comment]
@Gerald-ux-ux I found this and it helped me: https://github.com/contentlayerdev/contentlayer/issues/575

**Comment by Gerald-ux-ux** [comment]
@jkeussen Thanks bro

**Comment by dtechoracle** [comment]
nextjs-blog@0.1.0 dev
> next dev

  ▲ Next.js 14.2.3
  - Local:        http://localhost:3000
  - Environments: .env.local

 ✓ Starting...
Warning: Contentlayer might not work as expected on Windows
Contentlayer config change detected. Updating type definitions and data...
This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
https://github.com/contentlayerdev/contentlayer/issues

╥
╠══╦══╗
║  ║  ║
║  ║  ╠─An interrupt was produced by #39.
║  ║  ║
║  ║  ▼
║  ║
║  ╠─An unchecked error was produced.
║  ║
║  ║ TypeError: Cannot read properties of undefined (reading 'tracer')
║  ║     at f (file:///C:/Users/USER/nextjs-blog/node_modules/@effect-ts/system/_src/Effect/derive.ts:88:76)
║  ║     at IRead.f (file:///C:/Users/USER/nextjs-blog/node_modules/@effect-ts/system/_src/Effect/has.ts:113:33)
║  ║     at FiberContext.evaluateNow (file:///C:/Users/USER/nextjs-blog/node_modules/@effect-ts/system/_src/Fiber/context.ts:1136:31)
║  ║     at file:///C:/Users/USER/nextjs-blog/node_modules/@effect-ts/system/_src/Fiber/context.ts:576:33
║  ║     at file:///C:/Users/USER/nextjs-blog/node_modules/@effect-ts/system/_src/Support/Scheduler/index.ts:15:9
║  ║
║  ║ Fiber: #41 (started at: 2024-06-07T16:54:05.143Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #41 (started at: 2024-06-07T16:54:05.143Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #41 (started at: 2024-06-07T16:54:05.143Z) was spawned by:
║  ║
║  ║ Fiber: #39 (started at: 2024-06-07T16:54:05.142Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #39 (started at: 2024-06-07T16:54:05.142Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #39 (started at: 2024-06-07T16:54:05.142Z) was spawned by:
║  ║
║  ║ Fiber: #37 (started at: 2024-06-07T16:54:05.140Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #37 (started at: 2024-06-07T16:54:05.140Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #37 (started at: 2024-06-07T16:54:05.140Z) was spawned by:
║  ║
║  ║ Fiber: #26 (started at: 2024-06-07T16:54:05.123Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #26 (started at: 2024-06-07T16:54:05.123Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #26 (started at: 2024-06-07T16:54:05.123Z) was spawned by:
║  ║
║  ║ Fiber: #5 (started at: 2024-06-07T16:54:01.734Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #5 (started at: 2024-06-07T16:54:01.734Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #5 (started at: 2024-06-07T16:54:01.734Z) was spawned by:
║  ║
║  ║ Fiber: #0 (started at: 2024-06-07T16:54:01.699Z) was supposed to continue to: <empty trace>
║  ║
║  ║ Fiber: #0 (started at: 2024-06-07T16:54:01.699Z) Execution trace: <empty trace>
║  ║
║  ║ Fiber: #0 (started at: 2024-06-07T16:54:01.699Z) was spawned by: <empty trace>
║  ▼
▼

OS: win32 10.0.19043 (arch: x64)
Process: C:\Program Files\nodejs\node.exe C:\Users\USER\nextjs-blog\node_modules\next\dist\server\lib\start-server.js
Node version: v20.13.1
Contentlayer version: 0.3.4


I am having this above issue when trying to use notion with contentlayer after updating my contentlayer.config.ts file to this:

import { makeSource, defineDatabase } from "contentlayer-source-notion";
import * as notion from "@notionhq/client";

const client = new notion.Client({ auth: process.env.NOTION_TOKEN });

export const Post = defineDatabase(() => ({
  name: "Post",
  databaseId: "<databaseId>",
  query: {
    filter: {
      property: "Status",
      status: {
        equals: "Published",
      },
    },
  },
  properties: {
    date: {
      name: "Created time",
    },
  },
  computedFields: {
    url: {
      type: "string",
      resolve: (post) => `/posts/${post._id}`,
    },
  },
}));

export default makeSource({
  client,
  databaseTypes: [Post],
});
