### ISSUE TITLE
Be able to use workspaces dependencies and tsconfig paths in contentlayer.config.ts

### ISSUE THREAD

**Issue by gustaveWPM** [contentlayerdev/contentlayer#608]
Hello.

I think it would be great to be able to use workspaces and Typescript paths related dependencies in `contentlayer.config.ts`.

For instance, if I try it in my `tailwind.config.ts`
```ts
// tailwind.config.ts
import { buildPathFromParts } from '@repo/shared-lib/str';
console.log(buildPathFromParts('hello', 'world'));
```
All works as intended.

But if I do the same in `contentlayer.config.ts`

Then, I get an error:

```
ConfigReadError (/home/me/Delivery/project/contentlayer.config.ts): Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/me/Delivery/project/node_modules/@repo/shared-lib/str' imported from /home/me/Delivery/project/.contentlayer/.cache/v0.3.4/compiled-contentlayer-config-KYFR5QIE.mjs
ConfigReadError (/home/me/Delivery/project/contentlayer.config.ts): Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/me/Delivery/project/node_modules/@repo/shared-lib/str' imported from /home/me/Delivery/project/.contentlayer/.cache/v0.3.4/compiled-contentlayer-config-KYFR5QIE.mjs
```

It's quite annoying because I can't do anything other than imports with absolute or relative paths.
I can't use the paths in my `tsconfig.json`, and I can't use some of my third-party libraries, unless I adapt them entirely and have to write everything in relative or absolute path in them too.

---

EDIT: maybe it's related to ESBuild?

**Comment by gustaveWPM** [comment]
:<

**Comment by gustaveWPM** [comment]
.

**Comment by gustaveWPM** [comment]
.

**Comment by gustaveWPM** [comment]
:cry:

**Comment by gustaveWPM** [comment]
.

**Comment by zhutmost** [comment]
Hi, I have met a similar issue. Do you find any solutions?

**Comment by gustaveWPM** [comment]
no, sorry
