### ISSUE TITLE
Add support for Next 14+ => next-contentlayer

### ISSUE THREAD

**Issue by NBK-01** [contentlayerdev/contentlayer#615]
Can not use or install the next-contentlayer package when using NextJS 14.

**Comment by NBK-01** [comment]
there are only temporary solutions for npm, but shouldn't next-contentlayer have "next: latest" rather than 12 | 13

**Comment by ArmantG** [comment]
Project isnt being maintained until further notice from Netlify... Not sure of the details, just saw some comments on other issues. Very irritated with this, doesnt take much effort for them to just update the deps.... Seems utterly useless from such a big project everyone is keen to use...

**Comment by Hidde-Heijnen** [comment]
> Project isnt being maintained until further notice from Netlify... Not sure of the details, just saw some comments on other issues. Very irritated with this, doesnt take much effort for them to just update the deps.... Seems utterly useless from such a big project everyone is keen to use...

yeah @ArmantG it sucks tbh, any other solutions out there? Have been looking at @next/mdx + next-mdx-remote, but I honestly don't know where to go from here.

**Comment by ArmantG** [comment]
Next-mdx-remote or apparently react-markdown will work. There are plenty of example next js blog repos available of you search github using next-remote-mdx. Contenlayer is just so easy and convenient to use compared to these though. Hoping it picks up steam again but yeah, I'm in the same boat. I'm actually looking at Astro + backend. Astro supports md out the box and mdx with a simple add on install. Backend I'm looking at whether bun + hono might be worth my time and how to combine hono and Astro into one project. But havent had the chance to really sit so far these holidays.

**Comment by Hidde-Heijnen** [comment]
Yeah, I know how to set everything up, it's more that I really liked contentlayer and don't want to implement an alternative. But I guess I will now for my portfolio, since their communication is also mediocre

**Comment by Seokhyeon315** [comment]
@ArmantG Yeah I was very heavy user of NextJS and contentlayer but recently, I am trying to move to Astro framework

**Comment by witcradg** [comment]
Is this still a problem with Netlify? Can Vercel handle this?

**Comment by Seokhyeon315** [comment]
Contentlayer team hasn't updated anything that compatible with NextJS 14.I think it has nothing to do with the Netlify or Vercel. We can still use contentlayer with NEXTJS13 version but many people want to use latest features of version 14 as well.

**Comment by ArmantG** [comment]
Netlify bought the company who was sponsoring the project. The maintainer was receiving money from the sponsor which allowed him to spend more time on the project. Since the project isn't receiving funding and nobody knows whether Netlify will continue funding the project, its standing still... So yeah it does have to do with Netlify. It kinda works with Next 14 if you put some overrides in your package.json, but obviously long term it could become a problem if it isn't maintained to keep up with Next JS... Contentlayer basically only has one maintainer so yeah, doesn't seem like much will happen any time soon.
(I believe the information above is relatively accurate, but things could have changed since last I checked).

**Comment by AnweshGangula** [comment]
Contentlayer is probably not being maintained anymore as per this issue: #429

**Comment by AnweshGangula** [comment]
a PR #638 is currently in progress for this

**Comment by salvinoto** [comment]
So that's why it's showing version 13 on my 14 project....
