### ISSUE TITLE
Is this project unmaintained?

### ISSUE THREAD

**Issue by nickzelei** [contentlayerdev/contentlayer#616]
There hasn't been any activity on main or a release in about 3 months.

The last release was June 29th, which coincides with when Stackbit was [acquired by Netlify](https://www.stackbit.com/blog/stackbit-joins-netlify).

Are there any plans to restart effort on this? 
This project is getting a lot of attention with the rise of Shadcn, who uses contentlayer on his taxonomy website.

**Comment by nickzelei** [comment]
Just saw this post here in the announcement issue: https://github.com/contentlayerdev/contentlayer/issues/429#issuecomment-1731298319

Looks like there is currently no maintainer on this project until we here more from Netlify.

**Comment by zce** [comment]
https://github.com/zce/velite - Turns Markdown / MDX, YAML, JSON, or others into app's data layer with Zod schema.
