### ISSUE TITLE
Peer Dep Issue with next14

### ISSUE THREAD

**Issue by xyhomi3** [contentlayerdev/contentlayer#621]
```
➜ git:(main) ✗ npm install next-contentlayer          
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: d3vf0li0@0.1.0
npm ERR! Found: next@14.0.4
npm ERR! node_modules/next
npm ERR!   next@"^14.0.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^12 || ^13" from next-contentlayer@0.3.4
npm ERR! node_modules/next-contentlayer
npm ERR!   next-contentlayer@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/user/.npm/_logs/2024-01-02T17_10_00_401Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2024-01-02T17_10_00_401Z-debug-0.log
➜ git:(main) ✗ 
```

**Comment by omatheusant** [comment]
having the same issue!

**Comment by xyhomi3** [comment]
> having the same issue!

I found something that works for me

add this in your `package.json`
```json
  "overrides": {
    "next-contentlayer": {
      "next": "$next"
    }
  },
```
example
```json
{
  "name": "next14-cl",
  "version": "1.0.0",
  "private": true,

  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "postinstall": "prisma generate"
  },

 /**
 * @HERE

    "overrides": {
      "next-contentlayer": {
        "next": "$next"
      }
    },

**********************/

  "dependencies": {
    "next": "^14.0.4",
    "contentlayer": "^0.3.4",
    "next-contentlayer": "^0.3.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
  },

  "devDependencies": {
    "@types/node": "20.9.0",
    "@types/react": "18.2.46",
    "@types/react-dom": "18.2.15",
    "ts-node": "^10.9.2",
    "typescript": "5.2.2"
  }
}

```

**Comment by Jervx** [comment]
> > having the same issue!
> 
> I found something that works for me
> 
> add this in your `package.json`
> 
> ```json
>   "overrides": {
>     "next-contentlayer": {
>       "next": "$next"
>     }
>   },
> ```
> 
> example
> 
> ```json
> {
>   "name": "next14-cl",
>   "version": "1.0.0",
>   "private": true,
> 
>   "scripts": {
>     "dev": "next dev",
>     "build": "next build",
>     "start": "next start",
>     "lint": "next lint",
>     "postinstall": "prisma generate"
>   },
> 
>  /**
>  * @HERE
> 
>     "overrides": {
>       "next-contentlayer": {
>         "next": "$next"
>       }
>     },
> 
> **********************/
> 
>   "dependencies": {
>     "next": "^14.0.4",
>     "contentlayer": "^0.3.4",
>     "next-contentlayer": "^0.3.4",
>     "react": "^18.2.0",
>     "react-dom": "^18.2.0",
>   },
> 
>   "devDependencies": {
>     "@types/node": "20.9.0",
>     "@types/react": "18.2.46",
>     "@types/react-dom": "18.2.15",
>     "ts-node": "^10.9.2",
>     "typescript": "5.2.2"
>   }
> }
> ```

Thanks ma G 😄 💪🏼
