### ISSUE TITLE
Documentation Page Returning 500 Internal Error

### ISSUE THREAD

**Issue by rushi-mungse** [contentlayerdev/contentlayer#642]
## Issue Description:
When attempting to access the documentation page, users are encountering a 500 Internal Server Error. 

## Steps to Reproduce:

1. Navigate to the documentation page.
2. Attempt to access any section or resource within the documentation.

<img width="1440" alt="Screenshot 2024-02-19 at 10 45 20 PM" src="https://github.com/contentlayerdev/contentlayer/assets/86994311/ee314255-bb2a-4df5-bf3d-f1a986662db2">

**Comment by rushi-mungse** [comment]
I got temporary solution.
* [contentlayer vercel app ](https://website-git-new-landing-page-schick.vercel.app)

**Comment by OlekAleksander** [comment]
> I got temporary solution.
> * [contentlayer vercel app ](https://website-git-new-landing-page-schick.vercel.app)

Thank you!

**Comment by seancdavis** [comment]
Fixed with contentlayerdev/website#118
