### ISSUE TITLE
The site is down!

### ISSUE THREAD

**Issue by xingBaGan** [contentlayerdev/contentlayer#644]
https://contentlayer.dev/docs
![image](https://github.com/contentlayerdev/contentlayer/assets/53329437/f17af09b-4556-4938-96c2-86328faf5248)

**Comment by afullsnack** [comment]
was about to drop this issue as well, docs link has been down for a while now 😞

**Comment by sheaosaurus** [comment]
@xingBaGan Please see issue https://github.com/contentlayerdev/contentlayer/issues/429#issuecomment-1894971035. This project is no longer maintained.

**Comment by callumflack** [comment]
Could at the very least leave the docs up.

**Comment by callumflack** [comment]
https://website-git-new-landing-page-schick.vercel.app/docs

**Comment by MrMaina100** [comment]
> @xingBaGan Please see issue [#429 (comment)](https://github.com/contentlayerdev/contentlayer/issues/429#issuecomment-1731298319). This project is no longer maintained.

lol what ..

**Comment by seancdavis** [comment]
Fixed with contentlayerdev/website#118
