### ISSUE TITLE
The website documentation error.

### ISSUE THREAD

**Issue by arifinofficial** [contentlayerdev/contentlayer#648]
The documentation on the website is an error. I have been trying to access it for 2 days, but the error remains the same:"500 Internal Server Error".

URL: https://contentlayer.dev/docs

![Screenshot 2024-03-11 113159](https://github.com/contentlayerdev/contentlayer/assets/28805755/d9c82646-11c3-4356-a168-e99589cb0c8e)

**Comment by shashankboosi** [comment]
I came in here to raise the same but looks like it was raised 3 weeeks ago in here https://github.com/contentlayerdev/contentlayer/issues/642. 

Don't know if anyone is looking into this.

**Comment by shashankboosi** [comment]
Found this link that works from the other issue https://github.com/contentlayerdev/contentlayer/issues/644#issuecomment-1974403578

**Comment by arifinofficial** [comment]
Ahh, thank you @shashankboosi, until now I try to access the doc it's still an error. I'll try to use the web archive to access the documentation.

**Comment by seancdavis** [comment]
Fixed with contentlayerdev/website#118
