### ISSUE TITLE
Proposal to become a maintainer for Contentlayer

### ISSUE THREAD

**Issue by aelliixx** [contentlayerdev/contentlayer#651]
Hi! I've spoken with schickling late last year about continuing to support Contentlayer. Initially I suggested forking the project and there was some interest amongst the community on Discord. Schickling later suggested to create an issue offering my help on the main project instead. So that's what I'm doing :)

A little about me:
I'm a software developer working in the games industry but have been poking around in web for the last few years. I've been using Contentlayer for about a year in a number of different websites. I'm active on Discord and often try helping people who encounter issues there. I created a [plugin](https://github.com/aelliixx/rehype-cl-img) for managing Contentlayer images. More recently I have [rehosted the Contentlayer docs](https://contentlayer.aelliixx.com/) since the main website is down.

I'm not promising to bring Contentlayer up to date overnight nor very quickly either. I am, however, committed to keeping it maintained and used by the over 20,000 projects using it today.

My priorities would be to bring Contentlayer up to date with current NextJS versions, review and manage currently open pull requests, and work through the decent number of open issues.

Contentlayer is a brilliant tool that does what I want exactly how I want it. Maybe it's my stubbornness but I am not looking to use other content managers, so regardless if we can continue maintaining this project, I'll still keep using it and maintaining it for myself. So let's keep it going!

**Comment by thisislvca** [comment]
I'd love that!

**Comment by trebeljahr** [comment]
same here, please maintain this awesome project :)

**Comment by icco** [comment]
Yes! This would be great!

**Comment by herbievine** [comment]
Please!

**Comment by TheMikeyRoss** [comment]
we got your back 👍 once everyone realizes that PR's and Issues will actually be looked at then the repo will be active with PR's and Issues.

**Comment by TheMikeyRoss** [comment]
@schickling

**Comment by aelliixx** [comment]
> we got your back 👍 once everyone realizes that PR's and Issues will actually be looked at then the repo will be active with PR's and Issues.

That's the hope. I'm keen on investigating some open issues even right now, but I realise that whatever PRs one might make to resolve them wouldn't be merged in either.

And thank you and the rest of youse who've shown support on this issue and on Discord. It's clear that people are keen to use Contentlayer and keep it alive. Hopefully we see some movement on that end soon!

**Comment by TheMikeyRoss** [comment]
>  It's clear that people are keen to use Contentlayer and keep it alive.

Absolutely! One of the most popular projects of 2023 is using it! [shadn/ui ](https://github.com/shadcn-ui/ui/blob/main/apps/www/contentlayer.config.js) And many people (including myself) have used that docs as the foundation for our projects docs and now we're kinda stuck 😅

**Comment by jmatthewpryor** [comment]
any progress here?

**Comment by timlrx** [comment]
@aelliixx I spoke with Schickling as well and he gave me the go ahead to maintain an updated fork of it. It's now available at [Contentlayer2](https://github.com/timlrx/contentlayer2) and I have patched it based on my open pull request. Happy to get a few maintainers on board to restore other functionalities e.g. the website and chart a new roadmap.

**Comment by aelliixx** [comment]
That's fantastic, I'd be happy to help any way I can. First and foremost I'd be interested in bringing the main website up and running because that's what people have most issues with. I'm happy to host it at my expense, I just need the domain :)

**Comment by timlrx** [comment]
> That's fantastic, I'd be happy to help any way I can. First and foremost I'd be interested in bringing the main website up and running because that's what people have most issues with. I'm happy to host it at my expense, I just need the domain :)

This is going to be extremely difficult since it was bought over by Netlify. I can try asking the folks at Netlify nicely :) But, we should have a contingency plan.

**Comment by aelliixx** [comment]
Well I guess the first question would be if you're keen on continuing with the contentlayer branding (or if the licensing even allows for that).
Also, do you have a discord or someplace else we should continue these discussions as suspect we'll have smaller details to work out and this issue isn't the best place for it.

**Comment by Gerald-ux-ux** [comment]
Great idea man, this is definitely gonna help the community

**Comment by seancdavis** [comment]
Hey @aelliixx @timlrx and others: Thanks for starting this discussion!

I worked on Contentlayer with @schickling while at Stackbit, and I'm now over at Netlify. 

I'd love to see this project continue. We're currently in discussions about the most effective path forward. There's much to coordinate. It'll take some time, but we're making good progress.

In the meantime: 

- Use the [Contentlayer2](https://github.com/timlrx/contentlayer2) fork.
- The website is back up. As the fork gets updated, feel free to open PRs on the website repo and DM me on Discord (`seancdavis29`) for a review.

**Comment by Virous77** [comment]
Kudos to you man.

**Comment by TheMikeyRoss** [comment]
no :(

**Comment by sidwebworks** [comment]
If you use `pnpm` then you can do this using aliases
```
pnpm add contentlayer@npm:contentlayer2 next-contentlayer@npm:next-contentlayer2
```

**Comment by Fahad-Anyit** [comment]
Thank you, @seancdavis, for providing the up to date contentlayer2
