### ISSUE TITLE
"Get Started" throws error

### ISSUE THREAD

**Issue by omfischer** [contentlayerdev/contentlayer#652]
<img width="629" alt="image" src="https://github.com/contentlayerdev/contentlayer/assets/31882621/4857ea5f-67a0-42bc-8587-b50560cdc0a3">

Getting 500 "Internal Server Error" when pressing the "Get Started" button.

**Comment by immois** [comment]
Use this link [https://website-git-new-landing-page-schick.vercel.app/docs](url)
