### ISSUE TITLE
Contentlayer docs are down

### ISSUE THREAD

**Issue by janaHehr** [contentlayerdev/contentlayer#653]
Hi,
the docs are not available since days: https://contentlayer.dev/docs

`500` internal server error :(

**Comment by panosVegas** [comment]
still hapennign today (26/03/2024)

**Comment by colburncodes** [comment]
still down. 3/27/24

**Comment by wujihua118** [comment]
still down. 3/28/24
And thank you for sharing.

**Comment by zilahir** [comment]
still down :((

**Comment by igormcsouza** [comment]
still down! :D today april fools!

**Comment by seancdavis** [comment]
Fixed with contentlayerdev/website#118
