### ISSUE TITLE
Dev Server crashing

### ISSUE THREAD

**Issue by siyabendoezdemir** [contentlayerdev/contentlayer#659]
╥
╠══╦══╗
║  ║  ║
║  ║  ╠─An interrupt was produced by #39.
║  ║  ║ 
║  ║  ▼
║  ║
║  ╠─An unchecked error was produced.
║  ║ 
║  ║ TypeError: Cannot read properties of undefined (reading 'tracer')
║  ║     at f (file:///Users/siyabendoezdemir/Desktop/Projects/tweet-ai/node_modules/@effect-ts/system/_src/Effect/derive.ts:88:76)
║  ║     at IRead.f (file:///Users/siyabendoezdemir/Desktop/Projects/tweet-ai/node_modules/@effect-ts/system/_src/Effect/has.ts:113:33)
║  ║     at FiberContext.evaluateNow (file:///Users/siyabendoezdemir/Desktop/Projects/tweet-ai/node_modules/@effect-ts/system/_src/Fiber/context.ts:1136:31)
║  ║     at file:///Users/siyabendoezdemir/Desktop/Projects/tweet-ai/node_modules/@effect-ts/system/_src/Fiber/context.ts:576:33
║  ║     at file:///Users/siyabendoezdemir/Desktop/Projects/tweet-ai/node_modules/@effect-ts/system/_src/Support/Scheduler/index.ts:15:9
║  ║ 
║  ║ Fiber: #41 (started at: 2024-05-19T00:10:59.162Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #41 (started at: 2024-05-19T00:10:59.162Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #41 (started at: 2024-05-19T00:10:59.162Z) was spawned by:
║  ║ 
║  ║ Fiber: #39 (started at: 2024-05-19T00:10:59.162Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #39 (started at: 2024-05-19T00:10:59.162Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #39 (started at: 2024-05-19T00:10:59.162Z) was spawned by:
║  ║ 
║  ║ Fiber: #37 (started at: 2024-05-19T00:10:59.161Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #37 (started at: 2024-05-19T00:10:59.161Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #37 (started at: 2024-05-19T00:10:59.161Z) was spawned by:
║  ║ 
║  ║ Fiber: #26 (started at: 2024-05-19T00:10:59.158Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #26 (started at: 2024-05-19T00:10:59.158Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #26 (started at: 2024-05-19T00:10:59.158Z) was spawned by:
║  ║ 
║  ║ Fiber: #5 (started at: 2024-05-19T00:10:58.809Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #5 (started at: 2024-05-19T00:10:58.809Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #5 (started at: 2024-05-19T00:10:58.809Z) was spawned by:
║  ║ 
║  ║ Fiber: #0 (started at: 2024-05-19T00:10:58.800Z) was supposed to continue to: <empty trace>
║  ║ 
║  ║ Fiber: #0 (started at: 2024-05-19T00:10:58.800Z) Execution trace: <empty trace>
║  ║ 
║  ║ Fiber: #0 (started at: 2024-05-19T00:10:58.800Z) was spawned by: <empty trace>
║  ▼
▼

OS: darwin 23.1.0 (arch: arm64)
Process: /opt/homebrew/Cellar/node/21.6.1/bin/node /Users/siyabendoezdemir/Desktop/Projects/tweet-ai/node_modules/next/dist/server/lib/start-server.js
Node version: v21.6.1
Contentlayer version: 0.3.4

**Comment by dtechoracle** [comment]
I am currently having the same issues. Have you fixed yours?

**Comment by Virous77** [comment]
@siyabendoezdemir are you using nextjs?

**Comment by dtechoracle** [comment]
Yes, I am

**Comment by Virous77** [comment]
@dtechoracle for me it's working well here with Next.JS latest version. You can check the repo and version here. 

https://github.com/Virous77/Reetesh/tree/main/frontend

**Comment by ndom91** [comment]
Running into this too with the following relevant dependencies:

```
"dependencies": {
  "@notionhq/client": "^2.2.15",
  "contentlayer": "^0.3.4",
  "contentlayer-source-notion": "0.0.1-alpha.26",
  "fumadocs-contentlayer": "^1.1.34",
  "fumadocs-core": "12.2.4",
  "fumadocs-mdx": "8.2.33",
  "fumadocs-ui": "12.2.4",
  "next": "^14.2.4",
  "next-contentlayer": "^0.3.4",
  "react": "^18.3.1",
  "react-dom": "^18.3.1"
},
```

**Comment by matheuseabra** [comment]
I'm also having the exact same problem, any ideas to fix?
![Uploading Screenshot 2024-10-13 at 16.34.37.png…]()

**Comment by matheuseabra** [comment]
I'm also having the exact same problem, any ideas to fix?
<img width="1252" alt="Screenshot 2024-10-13 at 16 34 37" src="https://github.com/user-attachments/assets/d70cf594-102e-4772-ac0a-b2c2967185ad">

**Comment by Virous77** [comment]
@matheuseabra are you using Next.JS latest version?
