### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')

### ISSUE THREAD

**Issue by Virous77** [contentlayerdev/contentlayer#660]
```tsx
// NOTE use ESM/CommonJS compat import here until resolved: https://github.com/facebook/react/issues/11503
import React from 'react';
// NOTE use ESM/CommonJS compat import here until resolved: https://github.com/facebook/react/issues/11503
import ReactDOM from 'react-dom';
// @ts-expect-error React version workaround (This CJS workaround can be removed once Contentlayer is only targeting React 18+)
import { _jsx_runtime } from './jsx-runtime.cjs';
export const getMDXComponent = (code, globals = {}) => {
    const scope = { React, ReactDOM, _jsx_runtime, ...globals };
    const fn = new Function(...Object.keys(scope), code);
    return fn(...Object.values(scope)).default;
};
export const useMDXComponent = (code, globals = {}) => {
    return React.useMemo(() => getMDXComponent(code, globals), [code, globals]);
};
//# sourceMappingURL=useMDXComponent.js.map
```

This code is breaking when we are updating NEXT to version 15 and React to version 19. You can see the error in details below.

![Image 06-06-24 at 12 13 AM](https://github.com/contentlayerdev/contentlayer/assets/101452588/6ba761c3-2e4b-47d3-bbc6-1bd64f08d392)

**Comment by RhysSullivan** [comment]
@Virous77 did you find a fix? I'm looking into patch packaging it

**Comment by Virous77** [comment]
@RhysSullivan no not able to fix from my side yet.

**Comment by RhysSullivan** [comment]
@Virous77 couldn't find a fix I just removed content layer

**Comment by Virous77** [comment]
@RhysSullivan which other package you choose and my only concern are they support remark, rehype?

**Comment by nyxb** [comment]
Which react do you use? the error says that the react version is not compatible. So version 0.3.4 runs with all react 18 versions.

**Comment by Virous77** [comment]
@nyxb I upgraded to React RC and Next RC so i got that error. with next@14.2.3 and React@18.3.1 working well.

**Comment by nyxb** [comment]
> @nyxb I upgraded to React RC and Next RC so i got that error. with next@14.2.3 and React@18.3.1 working well.

yeah thats what i mean

**Comment by laem** [comment]
Same error here with next 15 RC / React 19.

**Comment by nyxb** [comment]
> Same error here with next 15 RC / React 19.

yeah u need to downgrade its not updated for react 19 its RC not finally

**Comment by abdokin** [comment]
you have to simply use MDXContent within "use client"

**Comment by Biyinzika-Joshua-J** [comment]
> you have to simply use MDXContent within "use client"

worked for me thanks

**Comment by Hiutaky** [comment]
> you have to simply use MDXContent within "use client"

Worked for me: 

- Next 15 and React 18
