### ISSUE TITLE
MDX files are not parsed correctly

### ISSUE THREAD

**Issue by alamenai** [contentlayerdev/contentlayer#664]
Hi everyone,

I started using content layer for my side project and I'm struggling to solve that issue of parsing my mdx files correctly.

I have this content structure

```
content
           |---chapters
                             |----chapter-01.mdx
                             |----chapter-02.mdx
          |---introduction.mdx
```

![image](https://github.com/contentlayerdev/contentlayer/assets/20143684/439730a0-bf53-4aac-90d7-386e903d921a)

## chapter-01.mdx

```
-------
title: Chapter 01
type: Chapter
date: 2021-12-24
---

# Chapter 01

import { Button } from "@/components/ui/button.tsx"

<Button >Click</Button>

```

## Contentlayer.config.ts

```ts

import { defineDocumentType, makeSource } from "contentlayer/source-files"
import remarkGfm from "remark-gfm"

export const Chapter = defineDocumentType(() => ({
  name: "Chapter",
  filePathPattern: `chapters/**/*.mdx`,
  contentType: "mdx",
  fields: {
    title: { type: "string", required: true },
    date: { type: "date", required: true },
  },
  computedFields: {
    url: {
      type: "string",
      resolve: (chapter) => {
        return `/chapters/${chapter._raw.flattenedPath.split("/").pop()}`
      },
    },
  },
}))

export const Introduction = defineDocumentType(() => ({
  name: "Introduction",
  filePathPattern: `**/*.mdx`,
  contentType: "mdx",
  fields: {
    title: { type: "string", required: true },
    date: { type: "date", required: true },
  },
  computedFields: {
    url: {
      type: "string",
      resolve: (introduction) => {
        console.log(introduction._raw.flattenedPath) // Debugging
        return `/introduction/${introduction._raw.flattenedPath
          .split("/")
          .pop()}`
      },
    },
  },
}))

export default makeSource({
  contentDirPath: "content",
  documentTypes: [Chapter, Introduction],
  mdx: {
    remarkPlugins: [remarkGfm],
  },
})

```

## Pages structrures

![image](https://github.com/contentlayerdev/contentlayer/assets/20143684/c0c3e86f-12c4-455b-a26d-08c85db129ba)

## Chapter page

```tsx

import { allChapters } from 'contentlayer/generated';
import { useMDXComponent } from 'next-contentlayer/hooks';
import { notFound } from 'next/navigation';

export async function generateStaticParams() {
  return allChapters.map((chapter) => ({
    slug: chapter._raw.flattenedPath.split("/").pop(),
  }));
}

const getChapter = (slug: string) => {
  return allChapters.find((chapter) => chapter._raw.flattenedPath.split("/").pop() === slug);
};

const ChapterPage = async ({ params }: { params: { slug: string } }) => {
  const chapter = getChapter(params.slug);
  if (!chapter) notFound();

  const Component = useMDXComponent(chapter.body.code);
  
  return (
    <div>
      <Component />
    </div>
  );
};

export default ChapterPage;

```

## Current

![image](https://github.com/contentlayerdev/contentlayer/assets/20143684/f95399d0-947c-404f-806c-ee1fdeba8a00)

## Expected

I expect the title `Chapter 01` to be bold and large because it starts with `#`.

**Comment by alamenai** [comment]
I figured out that I have to create independent `mdx.css` for styling them.

**Comment by Zer0xxxx** [comment]
> I figured out that I have to create independent `mdx.css` for styling them.

You can also give a look to https://github.com/shadcn-ui/taxonomy

**Comment by alamenai** [comment]
Thank you @Zer0xxxx , yes I guess this what I want exactly.

**Comment by Zer0xxxx** [comment]
> Thank you @Zer0xxxx , yes I guess this what I want exactly.

I don't know if it is _exactly_ what you want, but happy to feel helpful! 🧡

**Comment by Zer0xxxx** [comment]
@alamenai You could also give a look to this, which is also inspired from Taxonomy: https://www.youtube.com/watch?v=YC6LqIYVHxI

This might be helpful to you as well ~

**Comment by gustaveWPM** [comment]
Hi there!
I thought you might like to have a look at the repo I've been working on to get a ridiculously over-engineered codebase.
- https://github.com/Tirraa/dashboard_rtm

I did it mainly to progress in programming. Not everything in this project is perfect. I still have major performance problems in some places, and my breadcrumbs generated on the client side were actually a very bad idea.

(It increases the bundle size considerably and I suspect my performance problems are largely related to that, so it'll be one of the first things I change when I get a moment).

I don't have much time at the moment to improve this repo as we've been working with @Zer0xxxx on other projects atm. You can still try to get inspired by it and see if there's anything that interests you in this mountain of complexity. Don't be afraid to cherry-pick a bit if that helps.
