### ISSUE TITLE
Compatibility Request: Support for Next.js 14 in next-contentlayer

### ISSUE THREAD

**Issue by AcidOP** [contentlayerdev/contentlayer#665]
I'm currently using Next.js 14 and encountered a peer dependency warning when trying to install next-contentlayer:

Running `yarn add -D contentlayer next-contentlayer date-fn` yields the following error:

```bash
warning " > next-contentlayer@0.3.4" has incorrect peer dependency "next@^12 || ^13"
```

Latest Nextjs 15 is the latest version and this should be updated. 

Or maybe there is a workaround?

**Comment by Koala0CE** [comment]
I got the same issue here

**Comment by lukahukur** [comment]
Repo is dead, if you just starting new project avoid using this package.

**Comment by AcidOP** [comment]
Seems like this package is dead due to funding issues :(

**Comment by Koala0CE** [comment]
> Add this to your package.json to override the peer dependency version or use the maintained version of contentlayer called contentlayer2 ([#651 (comment)](https://github.com/contentlayerdev/contentlayer/issues/651#issuecomment-2030335434)):
> 
> ```json
> "overrides": {
> 
>     "next-contentlayer": {
>         "next": "$next"
>     }
> 
> }
> ```

I used the maintained version, thank you for letting us know about it.
