### ISSUE TITLE
Support for LaTeX

### ISSUE THREAD

**Issue by ajtadeo** [contentlayerdev/contentlayer#666]
Hello, I'm currently using this module for my blog and I'd love to see support for LaTeX to display equations and other math symbols from my markdown files. For example, I have this equation in my markdown file:

```md
$$1,124 mi/month  3 mi/kWh =374.667 kWh/month$$
```

but the rendered result is not converted into LaTeX formatting it just outputs the plain text.

**Comment by WendaoLee** [comment]
Request for this feature too.
