### ISSUE TITLE
App get crashed on Heroku 

### ISSUE THREAD

**Issue by Jerzac** [contentlayerdev/contentlayer#75]
## Anyone know what is the correct way to deploy on Heroku?
My `package.json` looks like and idk what could be the reason cause locally my app builds correctly 

 ```javascript
{
    "build": "npm run gen:contentlayer && next build",
    "gen:contentlayer": "contentlayer build --config ./contentlayer.config.ts --verbose",
    "start": "next start -p $PORT",
}
```

**Comment by schickling** [comment]
Could you please provide more information which errors you're seeing? Ideally both error logs and a little video demo of the problem.

**Comment by Jerzac** [comment]
My error was that I had `next-contentlayer` as `dev-dependency`
