### ISSUE TITLE
Examples are broken: no such thing as body.html

### ISSUE THREAD

**Issue by andresantosjor** [contentlayerdev/contentlayer#83]
The examples aren't working, because contentlayer doesn't expose the `html` property. the `body` property only has `_raw` and `code`. Check `/examples/starter/pages/posts/[id].tsx` to see the use of `<div dangerouslySetInnerHTML={{ __html: post.body.html }} />` return error.

contentlayer ^0.0.33

**Comment by schickling** [comment]
Thanks for opening this issue @andresantosjor. I've just tried running the [starter example](https://github.com/contentlayerdev/contentlayer/tree/main/examples/starter) and it seems to work as expected for me.

Is it possible that you're trying to use it with some MDX content? By default it's expecting plain Markdown content and doesn't expect MDX content.

**Comment by morganfeeney** [comment]
@schickling thanks for the info, but I think it could be made clearer, I had to focus on a file extension to understand this, it's easily missed.

Almost like if you imagine a tabbed view of the code, 2 tabs, 1 markdown, 1 mdx, then users could tab between them.
